### ISSUE TITLE
Ascent Guidance fails with empty Orbit inclination

### ISSUE THREAD

**Issue by mrmanc** [MuMech/MechJeb2#531] opened 2015-01-24 15:58 UTC
I recently found that on every launch as soon as the ship reached the gravity turn phase, MJ Ascent Guidance pointed the nose at the ground at about -45°, as if my command pod was the wrong way up. When it went below the height to start turning at (6.9km) it turned back to vertical ascent, and the process repeated.

I finally noticed that the Orbit inclination field was empty, so entered 0° and the problem went away.

I’m now unable to reproduce this, but I thought I’d report in case there is an obvious bug and in case other people experience the same.

Settings: Orbit altitude 71km, Orbit inclination empty, Prevent overheats enabled, Limit to terminal velocity enabled, Limit acceleration disabled, Limit throttle disabled, Force roll enabled, Limit angle of attack disabled, Corrective steering enabled, Autostage enabled, Auto-warp enabled.

MechJeb v2.4.2.0, KSP 0.9, no other mods installed.

**Comment by lamont-granquist** [comment] 2018-11-01 03:04
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 03:04 UTC
