### ISSUE TITLE
Feature Request: Assorted Ascent Guidance Features

### ISSUE THREAD

**Issue by macdjord** [MuMech/MechJeb2#612] opened 2015-06-05 00:39 UTC
- Limit Ascent Guidance Corrective Steering to positive pitch angles: Depending on how my TWRs change, some of my rockets end up on a higher trajectory than specified. COrrective steering tries to fix this, as it should, by pitching down below prograde. However, late in the flight, it sometimes ends up pointing _below the horizon_ - negative pitch values - in an attempt to get me back on the ideal course. This is obviously inefficient - I _want_ to go up, and burning down is counterproductive. I'd like an option that will prohibit corrective steering from going below the horizon.
- Smooth Throttle during coast to apoapsis: When coasting to apoapsis, the occasional burst of thrust is needed to counteract drag and keep the apoapsis at the target value. Currently, MechJeb does this by slamming instantly to full throttle for brief instants. It would be nice if it instead gently ramped up the throttle, to avoid unnecessary jerking.
- Early Circularization Burn When Necessary: Sometimes, with low target orbits and low TWR upper stages, MechJeb will achieve the target apoapsis, coast for a minute or two until we exit the atmosphere, and then plot the circularization burn only to find out that it should have started burning two minutes ago. It would be nice if it checked for this, and started the circularization burn early when necessary.

**Comment by RealKolago** [comment] 2015-06-05 01:29
I like to have more options to limit Ascent Guidance:
- Limit of max G's
- Limit of max Q
Throttle back the engines when reaching these limits.

**Comment by BloodyRain2k** [comment] 2015-06-05 01:40
MJ pitches below the horizon with a reason: the longer you stick close to the body you're escaping from (orbit or SoI doesn't matter) the less fuel you waste.

Ask Scott Manley how that oberth effect was doing that but I know from testing that making it not pitch leaves you with less dV left when your ascent is finished.

You can test it yourself and just compare MJ's launch with one where you fight the pitching constantly, I'd be surprised if you end up with more dV when you fought it.

Also when your rockets go up too straight, which also wastes fuel, limit that by thrustlimiting the engines in the editor, or try using MJ's thrustlimiter but so far I've had better results with adjusting the engines.


I second the smooth coasting btw, it's horribly how much stress the jerking causes when you coast with a mainsail or worse.

**Comment by futrtrubl** [comment] 2015-06-05 16:33
Re: RealKolago.
max G limit is already in, limit acceleration. G is just acceleration/9.8.
max Q could be nice.

**Comment by RealKolago** [comment] 2015-06-05 23:39
And how is this possible? 40.10 m/s2 at  1.7 G's: http://i.imgur.com/UvgSP9O.png

**Comment by sarbian** [comment] 2015-06-06 09:25
Current Acceleration report the engine stats only, drag & gravity are not accounted for. And the acceleration limits uses the same info.

**Comment by RealKolago** [comment] 2015-06-06 15:39
Thats the point. With mods like G-Force (http://forum.kerbalspaceprogram.com/threads/119518-1-0-2-G-Force-0-1-02-Beta) I like to throttle down the engines with the all this parameters accounted for.

**Comment by lamont-granquist** [comment] 2018-12-16 22:06
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

See also #1061

**Closed by lamont-granquist** 2018-12-16 22:06 UTC
