### ISSUE TITLE
Steering Issues

### ISSUE THREAD

**Issue by Tallinu** [MuMech/MechJeb2#57] opened 2013-04-14 12:07 UTC
Example stock craft with similar maneuvering characteristics to many ships that MJ has problems with: https://dl.dropboxusercontent.com/u/203721/MJ%20Maneuver%20Example.craft

To illustrate one of the biggest problems with MechJeb's steering (after launching, of course - path 0, 50, 0, 75% always works well):

Set SmartASS to Surf, heading 90, pitch 0 and execute.
Wait for ship to stabilize, and roll so that ship is level with horizon.
Leave RCS off, or disable it now.
Change Surf to heading 270, pitch -45 and execute.

Expected behavior: Simple (albeit slow) pitch down maneuver, rotating the ship through a 135 degree arc around the pitch axis. (Pitch control should reverse after traversing 67.5 degrees to avoid overshooting.)

Actual result: Pitch up and yaw left or right, combined with about 45 degrees roll, until target is on or near the ship's yaw plane. Continued yaw maneuver, most likely missing the target and sweeping back around in an arc, possibly overshooting several times. Total travel arc of 180 degrees or more even without counting the overshoot.

If the target orientation was a maneuver node (including automatic node execution) or "TGT +" instead of Surf, the ship tends to constantly roll left and right as well, and often starts off with a large, utterly pointless roll.

Since any two non-parallel vectors define a plane, MJ should simply be rotating the ship around the axis perpendicular to that plane. If that axis is not perfectly aligned with the ship's pitch or yaw axes, that shouldn't be a big deal either. The angle difference between that axis and the yaw or pitch axis, fed into the Sin and/or Cos functions, should be able to provide the appropriate yaw and pitch ratio. Scale both up proportionally so that the larger of the two reaches the max steering signal.

Then it's just a matter of getting it to quit overshooting the target heading by up to 90 degrees. **Update 4/21:** The moment of inertia calculations (#59) seem to be responsible for the inaccuracies leading to most steering overshoot. With the latest dev build and symmetric pod torque or enough RCS control, it can completely eliminate overshoot, so the PID controller itself is clearly working just fine in that regard.

**Comment by lamont-granquist** [comment] 2018-10-13 18:45
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

This is probably also a dup of #1050

**Closed by lamont-granquist** 2018-10-13 18:45 UTC
Labels: bug
