### ISSUE TITLE
Landing Guidance does not initiate

### ISSUE THREAD

**Issue by thebigschnoz** [MuMech/MechJeb2#1347] opened 2020-08-06 15:14 UTC
### MechJeb Version
2.10.0.0
### KSP Version
1.10.1
### Description
As reported here: https://www.reddit.com/r/KerbalSpaceProgram/comments/hrpbgx/mechjeb2_landing_guidance_not_working/
Seems to be an issue with landing guidance, both with the deorbit burn and final descent. Auto-warp does not activate from the beginning. If I manually activate auto warp, MJ will slow the warp, but nothing will still occur after. My gut tells me there's something causing an issue with the math, which is why the warp doesn't activate, as no math is completed.
### Replication Case
Personally attempted on Mun. Either choose a target or land somewhere.
### KSP.log
[output_log.txt](https://github.com/MuMech/MechJeb2/files/5035790/output_log.txt)

**Comment by lamont-granquist** [comment] 2020-08-06 23:46
dup of #992,  #967 and #1205 probably?

**Comment by zerg960** [comment] 2020-08-11 22:04
seem to be a different issue than auto-warp not working.

In my experience - landing guidance doesn't do the normal course correction bit that it's supposed to do when you select a landing site. Guidance just.. does nothing. I was landing on the Mun. Only way to get it to do something interesting is to select 'land anywhere'

Couple years ago landing guidance worked great.

**Comment by bunrotha** [comment] 2020-08-12 19:52
Been trying to isolate this in-game to see if I have the same issue.  Deorbit burn, plane change burn, and course correction all fail to activate throttle.  Course correction step is calculating and displaying the size of the burn, orients the ship to burn the right way, just.. not throttling up to do it.  Throttle remains locked as long as autoland is active.  Other steps don't display data for the burn, but exhibit similar behaviour.

Untargeted landings still activate throttle, going straight into the final descent stage.

**Comment by thebigschnoz** [comment] 2020-08-12 20:38
> Untargeted landings still activate throttle, going straight into the final descent stage.

See, for me, it doesn't matter on the type of landing - I still end up with nothing.

If needed, I can record a video and share.

**Comment by felixscheffer** [comment] 2020-08-14 12:56
I ran some tests with the latest dev build and had no issues. Both "Land at target" and "Land somewhere" worked just fine.  Maybe this has already been fixed. Have you tried the latest build? If you still have the issue, a video would be awesome.

**Comment by thebigschnoz** [comment] 2020-08-14 15:10
> I ran some tests with the latest dev build and had no issues. Both "Land at target" and "Land somewhere" worked just fine. Maybe this has already been fixed. Have you tried the latest build? If it still doesn't work, a video would be awesome.

Yes, this is actually only since the new update.

**Comment by zerg960** [comment] 2020-08-14 16:45
I've noticed that it only works after a quick-load (cause' the probe blew up the first time). It seems SOI changes make the land at target stop workin'.

**Comment by bunrotha** [comment] 2020-08-14 17:26
I reckon felixscheffer might have something there..
Problem was present in 2.10.0 release, cannot reproduce in 2.10.0.0-1009 build so far.
Running KSP 1.10.1.2939.
Will do a few more runs to see if I can reproduce using ships/conditions that have had the issue before.

**Comment by lamont-granquist** [comment] 2020-08-14 18:15
I just shipped a new dev with @felixscheffer's new fixes to landing guidance.  Also @sarbian fixed something awhile back.

**Comment by bunrotha** [comment] 2020-08-14 21:38
OK, results of further tests. 

Running 2.10.0.0 GA release, when this bug crops up, there is a lot of logspam "module MechJebModuleAttitudeController threw an exception in OnFixedUpdate: System.ArgumentOutOfRangeException: Index was out of range." and the same error in Drive module.  

The good news is that 
a) Save and Load seems to clear it.
b) Doesn't occur in 2.10.0.0-1010
Have flown the exact same ship from launch to landing on the same itinerary using both versions, and can reproduce OK in the GA release, but cannot reproduce in 1010 build.

Unless anyone can reproduce by another means, I'm confirming @felixscheffer's results, this seems fixed.

**Comment by lamont-granquist** [comment] 2020-08-14 22:14
Yeah logspam from the AttitudeController interacting with the NodeController was fixed by this:

https://github.com/MuMech/MechJeb2/pull/1316/files

**Closed by lamont-granquist** 2020-08-14 22:14 UTC
