### ISSUE TITLE
Mechjeb does not calculate next window for transfer to another planet correctly

### ISSUE THREAD

**Issue by kaflick** [MuMech/MechJeb2#241] opened 2013-11-23 22:08 UTC
Mechjeb2-2.1.0.0 (is this the latest?) does not calculate the next transfer window correctly.  If I do the transfer to another planet, wait until the node is set to activate in 9 days but then leave to check something else, when I come back (in just a few minutes with no time warp) Mechjeb says the next window is in 122 days.

How did the window in 9 days disappear?

**Comment by lamont-granquist** [comment] 2018-10-14 18:30
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 18:30 UTC
