### ISSUE TITLE
Maneuver nodes sometimes are not executed

### ISSUE THREAD

**Issue by Sagrer** [MuMech/MechJeb2#591] opened 2015-05-18 19:50 UTC
Sometimes when i click "execute" or "create and execute" - seems that MechJeb begin to execute the node - orientation changed to node point, engines control became locked, but then - there is no any warp, and engines never turn on even for +1s and more time for the node.

I can't understand how to reproduce this - it can happens with any craft, and if directly after this i switch to another craft to check - all nodes executed fine for this another craft, and when i switch back - nodes are still can't be executed. If i make some maneuvers by hands - after some time when i try to use MechJeb again - i notice that it works fine.

So, i archived my save and GameData (there are some mods needed to use the save) - there is a quicksave from the craft with this strange behaviour, it has a node which can not be executed. Actually the node can be removed, but any new nodes can't be executed too.

This is savefile https://drive.google.com/file/d/0B8cecT3boZX9UnU3eW9EMkRwVEk/view?usp=sharing
This is gamedata https://drive.google.com/file/d/0B8cecT3boZX9elBQZjJ2S3FEXzg/view?usp=sharing

I use MechJeb2 - 2.5.1.0 and KSP 1.0.2

**Comment by jacksonj04** [comment] 2015-05-20 16:08
:+1: for having observed this exact behaviour, including noticing that after manually manoeuvring MechJeb seems to regain control, but also unable to reproduce.

**Comment by Sagrer** [comment] 2015-05-20 17:54
also - somebody posted the same thing on forum
http://forum.kerbalspaceprogram.com/threads/12384-PART-1-0-2-Anatid-Robotics-MuMech-MechJeb-Autopilot-v2-5-1?p=1953796&viewfull=1#post1953796
http://forum.kerbalspaceprogram.com/threads/12384-PART-1-0-2-Anatid-Robotics-MuMech-MechJeb-Autopilot-v2-5-1?p=1953958&viewfull=1#post1953958
in this forum posts was something about using 2 MechJeb modules for different stages of the craft/

In my case - there was 2 MJ modules too. Initially it was 2-staged rocket, 0-stage was piloted spacecraft and 1-stage - the liquid-engine rocket, which may be returned back and recovered. First i landed and recovered 1-stage - MJ used to make deorbit burn with a maneuver node (landing autopilot was not used) - everything worked fine. Then i tried to make lunar flyby by maneuver node for 0-stage and MJ only made orientation for the node point, no warp and no burn was made by it.

**Comment by fdepee** [comment] 2015-05-27 11:43
Just wanted to mention this behavior I noticed in version MechJeb2-2.5.1.0-463
Not sure whether it's due to the same bug or perhaps related in some way.

Whenever I create nodes either through MJ or manually, and then click the "execute next node" button, my craft orients correctly and then immediately starts burning according to the node. So regardless whether the node is 10 seconds away or 10 days, it just burns the node directly after orienting, skipping warp entirely.

**Comment by Cosmius** [comment] 2015-05-27 18:06
Node execution fails randomly :(

**Comment by whensgen** [comment] 2015-05-27 18:12
I have this exact bug, affecting both drones and ships. Using ascent guidance, the ship coasts to the edge of atmosphere, changes to "circularizing", creates a node, aims, and fails to burn. Warp also fails, the ship does not attempt to warp in the two minute timeframe before the node. Interestingly with the main engines off, it will attempt the burn with RCS, but will not use RCS fuel during any other part of the launch

**Comment by sarbian** [comment] 2015-06-02 18:49
Should be fixed with 5a4b88906d5463904c17ac15e015dfcb39980795

**Closed by sarbian** 2015-06-02 18:49 UTC

**Comment by drasive** [comment] 2015-06-22 19:17
I can confirm that 5a4b88906d5463904c17ac15e015dfcb39980795 fixed it for me (tested with about 4 launches and 7 node executions). I used build [#480](http://jenkins.mumech.com/job/MechJeb2/480/).

**Comment by whensgen** [comment] 2015-06-22 19:21
I can confirm as well, though it has been fixed since 466 for me.

**Comment by 18001767679** [comment] 2022-06-17 02:40
Every craft that uses KAL overdriving to get fuel does not obey manuver nodes(there are 3 radially symetric mj cases and only one is green light)
