### ISSUE TITLE
Issues with 1.0.5/2.5.5.0

### ISSUE THREAD

**Issue by tms1979** [MuMech/MechJeb2#691] opened 2015-12-23 03:01 UTC
I started experiencing issues with the update to 1.0.5, so I updated to the new MechJeb and the issues got worse.

When I enter orbit do a circularize node, it doesn't wait until I reach the node to start the engines, but starts going as soon as it turns in the correct direction.

When landing I now always seem to overshoot the target by several kilometers (on Kerbin) to the North and East of the target. That is if my ship doesn't just burn up on re-entry because it's recorrecting too much and enters the atmosphere mid-correction and is facing the wrong direction. 

Both issues re-create with several attempts and re-installs of the game and mods.

Let me know if anything else is needed.

Using the following mods other than MechJeb (fully updated):
KFC (GN Drive)
AsteroidDay
DecayingRTGs
NearFutureProps
NearFutureSpacecraft
NearFutureConstruction
InterstellarFuelSwitch
NearFutureElectrical
NearFuturePropulsion
UmbraSpaceIndustries
SpaceY-Lifters

**Comment by sarbian** [comment] 2015-12-23 13:40
Ok, the mod list does not look crazy. Can you you share a log file and a save that make it easy to duplicate your problem ? I will have a look after Christmas.

**Comment by tms1979** [comment] 2015-12-24 00:17
[output_log.txt](https://github.com/MuMech/MechJeb2/files/71278/output_log.txt)

[persistent.zip](https://github.com/MuMech/MechJeb2/files/71279/persistent.zip)

Thanks for the quick reply. I wanted to triple check myself before having you dig deep, so I tried a different ship which may narrow down the issue. I'm bad - I run with the unlimited fuel, electricity and RCS cheat running, this may be important. I used a slightly modified Orbiter 1A with engines that can reach orbit and it circularized fine at the correct node. This still ended up overshooting the landing target by multiple km.

The issues are more apparent in my larger craft - Particularly the New Warp Science Ship. I've attached both ships also so you can check the designs and see if you can replicate the issues using them. The larger ship is the one where it doesn't wait to get to a node before engaging the engines and has much more trouble with landing.
[Ships.zip](https://github.com/MuMech/MechJeb2/files/71339/Ships.zip)

**Comment by lamont-granquist** [comment] 2018-12-16 22:30
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:30 UTC
