### ISSUE TITLE
Attitude Control

### ISSUE THREAD

**Issue by YpsilonTM** [MuMech/MechJeb2#804] opened 2016-10-15 21:46 UTC
Hi,

I am currently running build 2.5.9.0-643 (Dev Build 643)
When i change the attitude control to stock SAS, it doesn't do anything any more it just stays in its current position.
 [http://i.imgur.com/JFJygHY.png](http://i.imgur.com/JFJygHY.png)

**Comment by vitorboschi** [comment] 2016-10-19 20:25
Seens to happen on build #644 too

**Comment by lamont-granquist** [comment] 2016-11-24 05:20
Been trying to copy the MJ code to run the autopilot and this was driving me nuts.  Finally realized that the MJ code wasn't working so it wasn't too surprising my code wasn't working, either.

Looks like I'm on build 655.

I think the first problem is that the second argument to `SetTargetOrientation(Vector3 tgtOrientation, bool reset)` needs to be flipped around so its not resetting the PIDs every update, which i think will eliminate the wiggle, but then the problem is that it seems to be stuck in stability assist mode and won't track targets at all.

**Comment by lamont-granquist** [comment] 2018-12-16 22:46
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:46 UTC
