### ISSUE TITLE
Auto-warp switches off

### ISSUE THREAD

**Issue by fdepee** [MuMech/MechJeb2#412] opened 2014-08-05 00:53 UTC
Not sure if this is by design, but I remember the auto-warp checkbox to persist its state, so when you switched it on once in previous versions it remain switched on. In the latest versions (~July 2014 and later) it sometimes reverts back to off.

It's a bit confusing when doing complicated multipart dockings, having to do many consecutive burns when all of a sudden auto-warp reverts back and you're waiting in vain for the warp to start.

Nothing too big, but I've been surprised by it a few times. Is this done on purpose for a specific reason, or has a change in the code had this side effect?

**Comment by lamont-granquist** [comment] 2018-11-01 02:54
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 02:54 UTC
