### ISSUE TITLE
MechJeb survives re-entry explosion

### ISSUE THREAD

**Issue by StrangeBeing** [MuMech/MechJeb2#677] opened 2015-10-14 07:54 UTC
(Thanks so much for MechJeb!)

I occasionally attach MechJeb to a lower stage so that I can de-orbit debris.

Sometimes most of the stage (tanks, engines etc) explodes successfully in the upper atmosphere, but the MechJeb module survives. Unfortunately it can take many minutes to descend. During this time it is not possible to switch to other vessels, which might have important time-critical events occurring. This can be a real (KSP universe) problem!

Not to mention it is very boring watching the MJ casing falling from 30km...

I would suggest that if the part that MJ is attached to is destroyed, MJ itself should also be destroyed.

Many thanks!

**Comment by robot256** [comment] 2016-01-05 14:58
Oh man, I second this problem.  I like to put my Mechjebs inside a service compartment, so I wouldn't mind if they had heat/damage parameters.  I think you could add this with a Module Manager Patch file pretty easily and try it out.

**Comment by lamont-granquist** [comment] 2018-11-01 05:10
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 05:10 UTC
