### ISSUE TITLE
Mechjeb not circularizing at all when using ascent guidance and maneuver planner

### ISSUE THREAD

**Issue by mbkgit** [MuMech/MechJeb2#131] opened 2013-06-08 20:29 UTC
During the ascent stage, Mechjeb creates a node and upon arrival, says its circularizing but doesn't increase the throttle. Please help as when using the maneuver planner the same thing happens!

Thanks, mbkgit

**Comment by whensgen** [comment] 2015-05-26 02:46
My vessel is encountering this same bug. It is something new introduced in this version, since I flew the exact same craft yesterday with the previous version of MechJeb. The ship has RCS tanks and thrusters, turned on, and succeeds in lining itself up for the burn, but simply fails to actually engage the throttle once it reaches the node. For some reason, MechJeb refuses to use the RCS, of which there are 1500 units.

**Comment by copester** [comment] 2015-05-26 10:03
@whensgen, are you in career mode? The newest version intentionally shuts off the autopilot once the craft has left the atmosphere unless the Tracking Station has been upgraded.

**Comment by whensgen** [comment] 2015-05-26 10:05
I am in science mode, not career. The autopilot is still on, with a message
that says "circularizing", but it simply doesn't fire the engine once it
reaches the created node

**Comment by jacksonj04** [comment] 2015-05-27 11:35
Probably related to/duplicate of #591.

**Closed** 2015-06-02 20:45 UTC
