### ISSUE TITLE
MechJeb won't turn off

### ISSUE THREAD

**Issue by SpareBuffalo** [MuMech/MechJeb2#970] opened 2017-12-14 00:49 UTC
So I've been playing KSP since 2015, and I've been using MJ for very nearly as long. I've never had this problem before and I'm totally stumped!

For some reason, MJ requires that I point at 269 degrees heading. I can't turn it off, I don't have any things open, and it was like this when I opened the save. I'm fairly certain that I did nothing out of the ordinary when I left, but it's been nearly a month since last I played.

I could not find any Git issues relating to this, nor any Google leads. Apologies if there's something already in existence!

**Comment by lamont-granquist** [comment] 2018-12-24 19:21
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-24 19:21 UTC
