### ISSUE TITLE
Ascent Guidance, Launch at Interplanetary Window broken?

### ISSUE THREAD

**Issue by d3vi4nt1337** [MuMech/MechJeb2#990] opened 2018-02-11 16:31 UTC
I'm currently trying to get to Duna. Whenever i launch at interplanetary window and get into stable orbit. I open maneuver planner and select advanced transfer to another planet. But it appears im years away from an efficient maneuver. Shouldnt the ascent guidance be getting me into orbit at the best possible time?

**Comment by justhearit** [comment] 2018-09-22 05:05
Same here.. Always a year away after circularization

**Comment by lamont-granquist** [comment] 2018-12-24 19:30
duplicate of #763

**Closed by lamont-granquist** 2018-12-24 19:30 UTC
Labels: NEEDS MOAR TRIAGE, bug
