### ISSUE TITLE
MechJeb pod staging issue

### ISSUE THREAD

**Issue by daemonhat** [MuMech/MechJeb2#726] opened 2016-04-24 23:21 UTC
when using the mechjeb pod on a rocket as soon as the staging light turns green it simultaneously causes the ship to fire all engines, blow the decouplers, launch and explode. trying launch it by itself causes it to explode and launch at incredible speed(10k+ m/s). i'm using ksp 1.1 full release.

**Comment by adoo23** [comment] 2016-05-23 05:46
Similar problems here. Putting a mechjeb pod on my SSTO -> immediate explosion on the runway.

Tried just flying a mechjeb pod itself on the runway. After some collisions, the velocity suddenly jumped from 150m/s to a ridiculous 1500m/s.

**Comment by lamont-granquist** [comment] 2018-11-01 04:40
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 04:40 UTC
