### ISSUE TITLE
Support for other than stock fuels for dV calculation.

### ISSUE THREAD

**Issue by Zerg-152** [MuMech/MechJeb2#863] opened 2017-02-23 08:37 UTC
Hi, I created an engine which uses ExoticMatter as fuel, MechJeb cannot calculate dV parameters for that engine. The engine is really simple has 100kN max thrust has 100Isp and uses 1Exotic matter/s, Any way to modify somewhere for Mechjeb to be able to calculate dV for the Engine, which should be trivial only if the MJ could recognize Exotic Matter as a fuel.. ?

**Comment by sarbian** [comment] 2017-02-23 10:52
Mechjeb already supports non stock fuel and works fine with setups like real fuel.
You most are most likely hitting an other problem and I can't look into it without your mod.

**Comment by lamont-granquist** [comment] 2018-12-16 22:48
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:48 UTC
