### ISSUE TITLE
Loosing control at the end of maneuvers

### ISSUE THREAD

**Issue by noldaz** [MuMech/MechJeb2#178] opened 2013-07-28 21:42 UTC
everything is fine until few seconds before the end of the maneuver, then it wable around like crazy. Also mechjeb doesnt use asas at all and when mechjeb stop, the ship just rotate aimlessly.

the total mass of the AR202 case is 1E-05

**Comment by lamont-granquist** [comment] 2018-10-14 18:06
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 18:06 UTC
