### ISSUE TITLE
Swing-by Maneuver

### ISSUE THREAD

**Issue by DEvil0000** [MuMech/MechJeb2#92] opened 2013-05-12 09:23 UTC
I would like a swing-by/Gravity assist maneuver planer to minimize dV for e.g. planet transfers.
http://en.wikipedia.org/wiki/Swing-by

**Comment by lamont-granquist** [comment] 2018-10-13 18:40
Duplicate of #1051

**Closed by lamont-granquist** 2018-10-13 18:40 UTC
Labels: enhancement
