### ISSUE TITLE
Unable to use advanced transfer planner to return to Kerbin in 1.1.2.

### ISSUE THREAD

**Issue by ct9ars** [MuMech/MechJeb2#732] opened 2016-05-01 23:31 UTC
Just found this out trying to return three probes.  Attached is my output log, a screenshot, and below is the text from output log.  Using fresh install with just Mechjeb and Scansat.  Also tried full release and dev version.

ArgumentException: Getting control 6's position in a group with only 6 controls when doing Repaint
Aborting
  at UnityEngine.GUILayoutGroup.GetNext () [0x00000] in <filename unknown>:0 

  at UnityEngine.GUILayoutUtility.DoGetRect (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) [0x00000] in <filename unknown>:0 

  at UnityEngine.GUILayoutUtility.GetRect (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) [0x00000] in <filename unknown>:0 

  at UnityEngine.GUILayout.DoButton (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) [0x00000] in <filename unknown>:0 

  at UnityEngine.GUILayout.Button (System.String text, UnityEngine.GUILayoutOption[] options) [0x00000] in <filename unknown>:0 

  at MuMech.MechJebModuleManeuverPlanner.WindowGUI (Int32 windowID) [0x00000] in <filename unknown>:0 

  at MuMech.DisplayModule.ProfiledWindowGUI (Int32 windowID) [0x00000] in <filename unknown>:0 

  at UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID) [0x00000] in <filename unknown>:0 

  at UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
[output_log.txt](https://github.com/MuMech/MechJeb2/files/244393/output_log.txt)
![20160501192833_1](https://cloud.githubusercontent.com/assets/19141697/14944992/54e345a8-0fd3-11e6-8a78-a2e7e1af648d.jpg)

**Comment by billkerbinsky** [comment] 2016-05-02 22:36
Saw the same symptom (red square in advanced transfer planner porkchop plot) last night trying to return from Duna to Kerbin.

**Comment by sarbian** [comment] 2016-05-03 13:00
I found the source of the problem yesterday. A change in GetEccentricAnomaly impacts UpdateFromStateVectors. I need to check with @taniwha if the problem is with MJ code or the changes. Since it impacts UpdateFromStateVectors I don't think it is MJ. (it is not related to the deg=>rad change)

**Comment by sarbian** [comment] 2016-05-03 13:04
And for @taniwha sake. The problem manifest it self by "E is NaN!" spam. UpdateFromStateVectors calls it with an hyperbolic orbit and ta=Pi.

**Comment by TheKurgan** [comment] 2016-05-08 19:24
I know you said that it isn't MJ, but is there any viable fix for this... one that a user could apply in order to make my favorite mod work properly again?

**Comment by sarbian** [comment] 2016-05-08 20:30
Yes there is. But there is only so much hours per day and KSP is not how I spent 100% of my free time...
So wait.

**Comment by ct9ars** [comment] 2016-05-08 20:36
Thank you for working on a solution!

**Comment by TheKurgan** [comment] 2016-05-09 03:16
I apologize Sarbian, you misunderstood what I meant, I was not implying that you should get to work on it NOW...  I meant was there anything I could do... any work around or simple edit that a "user" could do. Yeah probably not...  Anyway, thank you for your work man, cheers.

**Comment by sarbian** [comment] 2016-06-28 10:00
This was fixed with the release of 1.1.3 and MJ 2.5.8

**Closed by sarbian** 2016-06-28 10:00 UTC
