### ISSUE TITLE
Mechjeb causes explosion of any VAB assembled craft upon loading

### ISSUE THREAD

**Issue by thegreenman95** [MuMech/MechJeb2#744] opened 2016-05-27 14:04 UTC
Upon loading a craft including the mechjeb pod, it explodes, quite dramatically. 
Windows 10
Running Kerbal x64
Used clean build for output log below
Only happening with mechjeb pod (not AR202 case)
Explosion of all craft upon loading, from the most basic rocket to more complicated stuff like space station sections
[output_log.txt](https://github.com/MuMech/MechJeb2/files/286572/output_log.txt)

Any help would be greatly appreciated :)

**Comment by drhay53** [comment] 2016-06-01 18:25
the current author does not have access to the necessary files for the pod, so this cannot be fixed. The pod cannot be used.

**Comment by lamont-granquist** [comment] 2018-11-01 04:39
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 04:39 UTC
