### ISSUE TITLE
No autopilot with mounted parachutes

### ISSUE THREAD

**Issue by Morgoth93** [MuMech/MechJeb2#606] opened 2015-06-03 19:19 UTC
When I mount the Mk2-R Radial-Mount Parachutes on my rocket mechjeb doesn't perform the maneuvers plotted by its autopilot. It Moves the rocket to the maneuver position but doesn't start the auto-warp nor the engine when it get's to the maneuver node.
I tested every part on my rocket and this happens only when i mounted this parachutes.

I am using mechjeb 2.5.1 on KSP 1.0.2.

**Comment by robot256** [comment] 2016-01-05 15:28
Either a) there was a bug with parachutes introduced with the aerodynamics updates and it's all fixed now, or b) adding the parachute changed the default staging sequence in such a way that the engine you want Mechjeb to fire is not turned on yet.  Did you double-check that the engine is activated and has fuel when you tell it to execute?

**Comment by lamont-granquist** [comment] 2018-12-16 22:10
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:10 UTC
