### ISSUE TITLE
Feature Request: Possibility to add main interface buttons to custom windows

### ISSUE THREAD

**Issue by MrGeekArt** [MuMech/MechJeb2#799] opened 2016-10-10 10:42 UTC
Hi Sarbian,
If possible, I'd like to have the option to add the buttons available in the main interface of MechJeb (like Ascent guidance, Attitude adjustement, ...) to a custom window.

This will enable me to keep said custom window open at all time and use it to open/close the other MechJeb modules I want without opening the main interface.
I hope I'm clear enough.

Many thanks for the time you're dedicating to this awesome mod, I really appreciate it.

**Comment by lamont-granquist** [comment] 2018-12-16 22:45
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:45 UTC
