### ISSUE TITLE
2.5 - Multiple craft with separate mechjebs don't keep SmartASS settings?

### ISSUE THREAD

**Issue by borogove** [MuMech/MechJeb2#581] opened 2015-05-08 15:48 UTC
While trying to dock two nearby craft, I usually set the passive craft to TGT+ and alternate the active craft between TGT+ and RVEL-. It seems like when I switch craft, it takes the SmartASS setting from the other and reorients instead of keeping what it was previously set to, which makes docking approaches pretty scary. It didn't used to do this in 2.4.

**Comment by lamont-granquist** [comment] 2018-11-01 04:15
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 04:15 UTC
