### ISSUE TITLE
[Career Mode] Researching AR202 Case does not unlock in editor

### ISSUE THREAD

**Issue by Brixmon** [MuMech/MechJeb2#245] opened 2013-11-30 04:41 UTC
I research the tech tree branch that gives you the MechJeb AR202 case. But when I visit the editor, it tells me I need to purchase it in R&D. The original AR202 case part is listed as owned, but a new duplicate case has been listed. Purchasing that and returning to the editor reveals the same problem, which repeats once before the parts stop duplicating and I still haven't got my MechJeb.

**Comment by lamont-granquist** [comment] 2018-10-14 18:31
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 18:31 UTC
