### ISSUE TITLE
Improve maneuver node editor

### ISSUE THREAD

**Issue by culebron** [MuMech/MechJeb2#210] opened 2013-10-14 13:26 UTC
I have 2 issues with it:
1. I have to write a lot in the time adjustment box. Maybe make it similar to vector editor? `[-] [value] [+]` This is the minimum adjustment that can ease a lot of pain. Maybe set some predefined values in it? 10 seconds, 1 minute, 10 minutes, 1 hour, 6 hours, 1 day, 1 week. This would ease the editing a lot.
2. I used this editor to shoot from Laythe to Kerbin directly. It's a lot cheaper than getting into Jool orbit, but a) Laythe has to be in a good position around jool, b) my ship has to be on the good side of Laythe.

I'd dispense with a "add/substract 1 orbit" option, but the best would be "add/substract 1 sidereal (grandparent body) orbit", i.e. later by 1 Laythe's orbit around Jool, and me still in the same position. I have no idea how to calculate this. At least +/- 1 orbit is clear and straightforward.

**Comment by lamont-granquist** [comment] 2018-10-13 21:45
think this got fixed a long time ago.

**Comment by lamont-granquist** [comment] 2018-10-13 21:45
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-13 21:45 UTC
