### ISSUE TITLE
Severe Aerodynamics Malfunction

### ISSUE THREAD

**Issue by Speleomantes** [MuMech/MechJeb2#679] opened 2015-10-25 03:08 UTC
**KSP:** 1.0.4 Windows 7 32 bit
**Problem:** Limit to terminal velocity is non-functional, Ascent Guidance begins gravity turn at ~300 m ASL
**Mods Installed:** MechJeb 2.5.3.0 (later 2.5.4.0 Build 516)
**Reproduction Steps:** Build a simple SSTO and launch using MechJeb's Ascent Guidance.
**Log:** http://m.uploadedit.com/ba3m/1445738957882.txt Output_log.txt

**Details:** 
- Finally upgraded to KSP 1.0.4 last night and after loading many mods onto it tinkered a bit in sandbox mode. MechJeb wouldn't keep craft under terminal velocity and Ascent Guidance began its gravity turn at ~300 m ALS. Components overheated on ascent with spectacular results. This rocket did not go to space today.
 
- Suspecting a mod conflict I installed a clean version of KSP 1.0.4 and built a simple brute force SSTO vessel consisting of a RockoMax Jumbo 64 feeding a Mainsail pushing a Mk I Pod and ancillary equipment (SAS, battery, etc.). Flew it into orbit by seat-of-the-pants flying to see that it could make it.

- Downloaded a new version of MechJeb 2.3.5.0 from Curse and installed it. Restarted the game and added the AR202 to the Mk I. Launched with Ascent Guidance and got the same problem.

- Checked here and found Molsen23's issue: https://github.com/MuMech/MechJeb2/issues/673 Downloaded Build 516 of the dev version as suggested by sarbian. Same problem, however:

- The "Limit Q to:" utility works as a very kludgy work-around. This indicates that MechJeb can control the throttle but isn't calculating terminal velocity properly. My suspicion is that this arises from the new aerodynamics introduced in KSP 1.0.x, which MechJeb isn't reading properly yet. The consequence is that many of the MechJeb components aren't recognizing Kerbin's atmosphere, leading to an infinite terminal velocity and an extremely premature gravity roll.

**Temporary Fix:** It's Ugly but
- Download and install the latest stable dev build (https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/)
- Set "Limit Q" to about 10,000 (this will vary from craft to craft)
- Use Smart ASS -> Surface -> Up for the vertical ascent portion
- Engage the autopilot once your craft reaches ~8000 m ASL

If anybody has a better idea let me know.

**Suggestion:** I know, this is already TL;DR but "Limit Q to X" isn't entirely effective at preventing the wonderful new world of component overheat on ascent. I had to tone it down from 20,000 to 10,000 to keep all the bits on my ship on the way up. A "Prevent/Limit Component Overheats" utility might be very helpful.

Thanx,
-S

**Comment by sarbian** [comment] 2015-10-25 09:06
>This indicates that MechJeb can control the throttle but isn't calculating terminal velocity properly
Nope. Terminal velocity is perfectly fine but the 1.0.x aerodynamic make it a very high number, just like in real life. Limiting to terminal velocity is way less useful in 1.0.x than it was before.

>Ascent Guidance begins gravity turn at ~300 m ASL
Welcome to 6 month ago. A new option was added in the ascent path editor. Have a look. FYI this allow for a more optimal trajectory in line with those used IRL.

>A "Prevent/Limit Component Overheats" utility might be very helpful.
Clearly but the new KSP heating is quite complex and I don't have a magic temperature number I can watch. Some part are hot by design (then engine and the part near them) and some other part should be kept 'cold'. I don't have the code that tells me which one you want to keep cold.

That said others mange to reach orbit fine with the current code so you may also want to reflect on your designs.

I am closing the ticket since there is no "Severe Aerodynamics Malfunction". If you want to open a new one for a more specific issue feel free to do so.

**Closed by sarbian** 2015-10-25 09:06 UTC

**Comment by Speleomantes** [comment] 2015-10-27 04:37
If it were an issue with a single craft I'd be inclined to agree. I initially had the problem with several more elegant craft so I made a clean install of KSP and MechJeb both and built that Brute-Force-N-Ignorance rocket solely for testing purposes. I'm still having the same problems with completely unrelated craft two days later.

Also:
- My admittedly very ugly craft reached orbit when controlled manually. Not pretty but it got there.
- Craft design shouldn't affect whether it throttles down at terminal velocity. So long as it's capable of achieving Vt and isn't firing SRBs or something else unthrottlable.
- Craft design shouldn't cause a gravity turn at 300 m ASL either. This is not a topple, it's a controlled pitch over to ~60 degrees to the East with the words "Gravity Turn" where Ascent Guidance normally reads "Vertical Ascent" up to about ~8000 m.

I don't wish to annoy but I feel that I've been reasonably thorough in taking the correct measures before bringing this to your attention. Whether or not heeling over at 60 degrees to port and failing to engage throttle limiter shortly after lift-off is a "Severe Aerodynamics Malfunction" is a matter of semantics. That and "Major Malfunction" was already taken.

The problems that I described remain. Having done what I think is a reasonable job of reporting them to you I'd appreciate it if you could take the relatively simple steps necessary to replicate them. Precious little point in having a bug reporter otherwise.

Please advise if you would like me to proceed in some other manner.
-S

**Comment by sarbian** [comment] 2015-10-27 13:27
My reply formatting was messed up so you may have missed some of my points (I edited it but I will repeat them anyway)

* I doubt you are reaching terminal velocity with the new aero. 

* look at the options in ascent guidance patch editor and you ll notice that there is new settings. This setting is why you turn earlier.

You find me quite dismissive of your problem because I already dealt with exactly the same feedback when 1.0.x got out and I already explained multiples times the source of those problem (most of them have nothing to do with MJ)

That said if you share your craft file and settings I would happily test it myself to see if it exhibit some new behaviors I don't know about.

**Comment by Speleomantes** [comment] 2015-10-28 21:10
You're right, I was unable to see the bulk of your reply. Thanks for the explanation. It makes it much clearer now. The gravity roll at 300 m makes perfect sense if Squad's cranked Vt way up. Also explains why I'm having trouble getting down to safe parachuting speed. Drogue chutes are my new best friend.

That Q limitter you're implementing should come in very handy given that you can now build ships that will cheerfully burn up while leaving the atmosphere.

I won't pretend to understand how Squad's working the game mechanics for the temperatures but I suspect that you could implement a "Prevent Component Overheats" by linking an MJ throttle control to the heat warning bar that pops up once a component starts to warm beyond a certain tolerance (I think Squad is using 50% but that's just eyeballing it).

Alternately, if each component has a T and Tmax variable you could let users select what perentage of Tmax T should reach before throttling back. That depends on how Squad's implemented component heating though.

And yes, I know this is so very 6 months ago but some of us have been contentedly playing 0.2.5 while waiting for our favorite mods to catch up. We're Luddites, I know.

Thanx again,
-S
