### ISSUE TITLE
Windows not remembered on per-vessel basis

### ISSUE THREAD

**Issue by BloodyRain2k** [MuMech/MechJeb2#909] opened 2017-07-10 09:32 UTC
A longer while ago, I think before 1.2, MJ was able to remember which windows were open per-vessel.

So for example I could have a rover on the Mun and the Rover AP open on that and if I were to switch to a spaceplane on Kerbin that I left having the Spaceplane AP open instead then that's what I would get to be open when I switch to it, and if I were to switch back to the rover I'd have the Rover AP open again.

However that seems to be pretty broken now with 2.6.1.0 (and was already with 2.6.0.0 too), atleast for me.
What I currently have is one global window layout and that's it.
If I leave a rover with the Rover AP open and switch to anything else I will still have the Rover AP open after switching, and if I close it and go back to the rover that is supposed to have it open it would stay closed.

**Comment by lamont-granquist** [comment] 2018-12-24 19:15
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-24 19:15 UTC
