### ISSUE TITLE
Create "common" features control dialog to enable them across all functions and consolidate them

### ISSUE THREAD

**Issue by mbainrot** [MuMech/MechJeb2#108] opened 2013-05-26 03:06 UTC
Create a dialog for controlling common features such as "Auto Throttle", "Auto Stage", "Auto Warp", etc and then enable them for Orbital operations, landing autopilot? (warp would be nice, auto stage would help but not sure if having to rely on it is a good sign ;) )

Also from my observations auto throttle? seems to affect other modules, hence the consolidation suggestion.

P/s Ty for the awesome work. makes my landings alot-less-shake-inducing :)

**Comment by robot256** [comment] 2016-01-19 21:14
It seems like most of this suggestion is already achieved in the "Utilities" window, and the custom window editor can achieve the rest.  Am I right?

**Comment by lamont-granquist** [comment] 2018-10-13 18:50
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-13 18:50 UTC
