### ISSUE TITLE
Overkill when aligning

### ISSUE THREAD

**Issue by hehe3301** [MuMech/MechJeb2#369] opened 2014-05-28 16:43 UTC
Whenever trying to align an extremely agile ship for a maneuver/landing/docked/etc. the ship spins much faster then mechjeb can handle and begins spinning out of control, almost always missing the maneuver. perhaps if you could detect how fast the ship is changing direction and throttling down on the orientation?

**Comment by lamont-granquist** [comment] 2018-10-14 21:09
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

Plus #1050

**Closed by lamont-granquist** 2018-10-14 21:09 UTC
