### ISSUE TITLE
Elevation angle from land location; longitude for planned stationary orbit

### ISSUE THREAD

**Issue by diomedea** [MuMech/MechJeb2#281] opened 2014-01-15 16:13 UTC
Among all the info that MJ provides, there is one I would find useful but seems missing. That is the angle above the local horizon (generally called "elevation") that a target landspot would have while looking at the current craft. It comes very useful when , e.g., there is need to know what margin of visibility (as elevation above the horizon) still exists from those two landspot and craft. There is no simple way I know of to have that angle from other values local to the craft, as the local horizontal plane is different (the difference is another angle given by combining both the differences in latitude and in longitude) and therefore the elevation is not simply the reverse of the pitch while the craft is pointing back at the target.

Similarly, I find a missing bit with the maneuver planner, as it is designed now. 
It would be useful, e.g. while planning for insertion to a stationary orbit above a body, to be able to specify a specific longitude where the craft will be (or, the longitude of the point projected on the surface of the body along the stright line from the craft to that body center). While it is not too difficult to find the final longitude with an existing transfer orbit (as the time to the apoapsis gives out how much the body will have rotated in the meantime), there is nothing to let this "longitude" be specifically planned for in MechJeb.

**Comment by lamont-granquist** [comment] 2018-10-14 18:51
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 18:51 UTC
