### ISSUE TITLE
Suggestion: more RCS fuel efficiency when rotating ship in space

### ISSUE THREAD

**Issue by zero87** [MuMech/MechJeb2#487] opened 2014-12-02 23:54 UTC
When Manouver planner is told to execute the next node it burns RCS fuel until it is halfway through and then it starts to burn in the opposite direction until the ship is alligned for node execution. This is the most time-saving method but consumes a lot of RCS fuel.
It would be nice to have an option to choose between this option and another one which just burns a little RCS fuel to spin the spaceship and then pyhsics warp until it reaches the allignment for the burn.
This would take longer but save on RCS fuel.
Perfection would be if Mechjeb knew how much time is left until burn and then use just as much RCS fuel as needed to allign the ship in time.

**Comment by gmcnew** [comment] 2015-05-03 18:37
If you have reaction wheels, you can work around this by disabling "Use RCS for rotation" in the SmartRcs window.

**Comment by robot256** [comment] 2016-01-20 18:24
I confirmed that the latest Mechjeb version does in fact incorporate this suggestion.  Regardless of whether RCS is there or not, it will give a torque impulse to accelerate, then coast, then another impulse to decelerate.  It works much better this way.

As far as I know, Mechjeb intentionally does not use physics warp because it causes too many problems for too many people.  Personally, I think the present RCS-saving turn style combined with standard warp is sufficient.  Sarbian can close this ticket if he agrees.

**Comment by lamont-granquist** [comment] 2018-10-13 18:15
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-13 18:15 UTC
