### ISSUE TITLE
Rendezvous autopilot fails to match planes

### ISSUE THREAD

**Issue by BIGMOS** [MuMech/MechJeb2#121] opened 2013-06-01 14:22 UTC
Hi mechjeb fubars at at maching planes when using rendezvous autopilot every time. I am using 0.20.2.186 of ksp. It say 68 years, also it flys past manever node and Never matches palnes

**Comment by lamont-granquist** [comment] 2018-10-13 20:00
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-13 20:00 UTC
