### ISSUE TITLE
Request : Add setting to 'activate stock SAS on warp' for users of PersistentRotation

### ISSUE THREAD

**Issue by KSPjohnFX** [MuMech/MechJeb2#603] opened 2015-06-02 18:44 UTC
With the mod PersistentRotation any rotation remaining when on rails warp is activated continues to move the craft away from the maneuver node meaning an almost endless cycle of (aim at node, warp, node drift, stop warp, aim at node). This is especially problematic if Saturatable Reaction Wheels are also installed. If the stock SAS is activated this does not happen and the correct heading is maintained. The least effort solution I can imagine would be for Mechjeb to have a toggle setting (off by default) to 'activate SAS on warp'. If this small change could happen it would improve usage for users of PersistentRotation while leaving function untouched for other users of Mechjeb.

Thank you.

**Comment by sarbian** [comment] 2015-06-02 18:50
Duplicate of #589

**Closed by sarbian** 2015-06-02 18:50 UTC
