### ISSUE TITLE
No toolbar and exploding command module

### ISSUE THREAD

**Issue by MrMiyagiEng** [MuMech/MechJeb2#729] opened 2016-04-25 19:57 UTC
Hello,

I am pretty new to modding but i seem to have the jist of it until the release of KSP 1.1. I redownloaded and installed all of my mods and didn't realise that the Mechjeb wasn't working until I unlocked it in the tech tree. I have tried deleting all of my other mods and also moving the KSP files to my D: drive but to no avail. I also tried to use the MJ command module but it apparently explodes on loading.

[KSP.zip](https://github.com/MuMech/MechJeb2/files/235303/KSP.zip)

**Comment by MrMiyagiEng** [comment] 2016-04-26 19:34
Update for those with similar issues:

I reinstalled MechJeb2 today using CKAN and it works pefectly. I am yet to test the exploding module but i now have guidance again!

**Comment by MrMiyagiEng** [comment] 2016-04-26 19:36
still explodes but the case is now functional so i can get by

**Comment by lamont-granquist** [comment] 2018-12-16 22:16
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:16 UTC
