### ISSUE TITLE
Index Out Of Range Exception

### ISSUE THREAD

**Issue by marosciacchitano** [MuMech/MechJeb2#536] opened 2015-01-29 07:38 UTC
Having been getting this with the latest Dev Build (#399) and the latest stable release (2.4.2)

> IndexOutOfRangeException: Array index is out of range.
>   MuMech.MechJebPod.Update ()

KSP.log is filled with this error message. I wish I knew how to reproduce the error. Perhaps something to do with vehicles that have multiple Mechjeb Instances, such as docked ships? (Just a guess thought, could be a red herring)

Edit: This may be a result of my meddling with module manager:

> @PART[*]:HAS[@MODULE[ModuleCommand]]:Final
> {
>   %MODULE[MechJebCore]
>   {
>       MechJebLocalSettings
>       {
>   MechJebModuleCustomWindowEditor { unlockTechs = flightControl }
>   MechJebModuleSmartASS { unlockTechs = flightControl }
>   MechJebModuleManeuverPlanner { unlockTechs = advFlightControl }
>   MechJebModuleNodeEditor { unlockTechs = advFlightControl }
>   MechJebModuleTranslatron { unlockTechs = advFlightControl }
>   MechJebModuleWarpHelper { unlockTechs = advFlightControl }
>   MechJebModuleAttitudeAdjustment { unlockTechs = advFlightControl }
>   MechJebModuleThrustWindow { unlockTechs = advFlightControl }
>   MechJebModuleRCSBalancerWindow { unlockTechs = advFlightControl }
>   MechJebModuleRoverWindow { unlockTechs = fieldScience }
>   MechJebModuleAscentGuidance { unlockTechs = unmannedTech }
>   MechJebModuleLandingGuidance { unlockTechs = unmannedTech }
>   MechJebModuleSpaceplaneGuidance { unlockTechs = unmannedTech }
>   MechJebModuleDockingGuidance { unlockTechs = advUnmanned }
>   MechJebModuleRendezvousAutopilotWindow { unlockTechs = advUnmanned }
>   MechJebModuleRendezvousGuidance { unlockTechs = advUnmanned }
> 
> ```
>   }
> ```
> 
>   }
> }

**Comment by lamont-granquist** [comment] 2018-11-01 03:57
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 03:57 UTC
