### ISSUE TITLE
Mechnical Jeb - Pod Version 2.0 researched but not available in VAB

### ISSUE THREAD

**Issue by payonel** [MuMech/MechJeb2#824] opened 2016-11-29 06:29 UTC
I have just researched (purchased with science) "Automation" and yet the pod is not available in VAB. Note that the other 2 items in the "Automation" group are available in VAB now, namely the "MK2 Drone Core" and the "Communotron HG-55"

game version: 1.1.3.1289 (x64)
mechjeb version: MechJeb2-2.5.8.0

**Comment by lamont-granquist** [comment] 2018-12-16 22:37
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:37 UTC
