### ISSUE TITLE
Auto-warp and/or dropping out of user warp for "Land anywhere"

### ISSUE THREAD

**Issue by tavert** [MuMech/MechJeb2#41] opened 2013-04-10 02:00 UTC
Land at target seems to now know when it will need to start its braking burn and auto-warps there automatically. Can the same functionality be added to "Land anywhere"? Or if the user is time warping too aggressively, needing to start the braking burn is a good reason to drop out!

**Comment by lamont-granquist** [comment] 2018-10-13 18:31
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-13 18:31 UTC
