### ISSUE TITLE
[Bug] Aborting from Maxwarp in Warp Helper changes flight path [2.1.1]

### ISSUE THREAD

**Issue by Flatfoot** [MuMech/MechJeb2#286] opened 2014-01-22 05:17 UTC
In 2.1.1 [KSP 0.23] I've noticed several times when using the Warp Helper aborting from max warp value will cause your flight path to jump.  I usually see it when I'm using Warp to SOI transition and realize I want to adjust something.  When I hit abort, it instantly drops it down to x1 instead of allowing it to scale down. 

   I'm no software coder; but my recommended fix is having the abort do a rapid scaled drop down to 1, or another value that won't impact the actual flight path.

It's annoying to see all your efforts setting up for a near perfect gravity brake into high Jool orbit via Vall get squashed because of this.

**Comment by lamont-granquist** [comment] 2018-10-14 18:43
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 18:43 UTC
