### ISSUE TITLE
RealFuels RCS silliness

### ISSUE THREAD

**Issue by NatefromNC** [MuMech/MechJeb2#665] opened 2015-09-02 02:53 UTC
First of all, MechJeb _does_ recognize the RealFuels stuff as propellant for the RCS system, so you're one better than stock SAS.
However, the ONLY way that you can get it to point in the right direction is by using thrust vectoring- and no, that was not a RO issue, as I was using the biggest RCS quads available on a relatively small craft. MechJeb is FAR too eager on the throttle with RCS, not turning it off until well after it's crossed the point it needs to be at. For RO usage, it just needs to provide a love tap in the right direction, wait a bit, then provide an equal and opposite love tap once it's aligned with the node.
Also, could you make the RCS translate forward while staging to take care of the ullage? Thanks...

**Comment by xATHEISTxDEITYx** [comment] 2016-02-07 21:34
I've been having a similar issue recently with mechjeb overcontrolling way past the point of the maneuver node, then overcorrecting back again. I't causing my ships to tumble out of control.

**Comment by kiwivogel** [comment] 2016-03-11 14:53
I get the idea this isn't just the case with RCS. If you rely on vernier engines for attitude control MJ tends to go wild on those as well. (For instance with raider nicks, zenith or soyuz.) It might just be that MJ has issues with engines gimballing on a single axis but I have no information to back that up.

**Comment by BloodyRain2k** [comment] 2016-03-13 17:24
There actually was a bug long ago where MJ was less stable with gimbaled engines than without, but that was somewhen fixed, so maybe these just bring the issue back because their gimbal is larger, for whatever reason.

One thing to try would be to disable or reduce the gimbal to 'normal' ranges and see if the issue goes away.

Different PID values can also help, I'm using different than default and I tend to have less issues with mine.
	TfMin = 0.1
	TfMax = 0.75
	kpFactor = 2
	kiFactor = 16
	kdFactor = 0.4

**Comment by lamont-granquist** [comment] 2016-12-13 05:00
@sarbian this is likely just the rcs torque issue fixed awhile ago

**Comment by lamont-granquist** [comment] 2018-11-01 04:46
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 04:46 UTC
