### ISSUE TITLE
Feature Request: Should not need mechjeb module on craft to see Delta-V in VAB

### ISSUE THREAD

**Issue by macdjord** [MuMech/MechJeb2#607] opened 2015-06-04 21:52 UTC
There is no reason that a craft should have to have MechJeb capability in order to see the Delta-V Info and Ship Info boxes in the VAB and Hangar.

**Comment by lamont-granquist** [comment] 2018-12-16 22:12
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:12 UTC
