### ISSUE TITLE
Serious issues.

### ISSUE THREAD

**Issue by Mike0190** [MuMech/MechJeb2#620] opened 2015-06-11 09:42 UTC
Okay.. So I've been playing ksp for awhile and I decided to start using Mechjeb 2.5.1. Today because I was tired of doing orbits over and over. When I first started using it, it worked like a charm, I kept using it a few more times getting the feel for everything and all of a sudden (using the same ship that I had no problems with the first couple times) I started noticing I had less and less fuel at the same orbit, after trying over a few times Mechjeb now isn't even able to get a ship with 8000 delta-v and a TWR of 2.8 into a 70km orbit.. It actually starts loosing altitutde around 16k now and starts turning back to Kerbin. Keep in mind I used the exact same settings (I made sure to hit reset settings to default multiple times) and I'm using the exact same ship it had no problem getting all the way to the mun and back the first time.. I have no idea what's going on.

**Comment by sarbian** [comment] 2015-06-11 09:51
Welcome. The current official release is a bit outdated and I am waiting for the release of KSP 1.0.3 to have a new one. I recommend that you try the current dev release in the mean time : http://jenkins.mumech.com/job/MechJeb2/

That said I have no idea of what is going on for your. When you say you have 8k dV is it Vacum dV or ground ? Display the full stats and look at the Sea level infos. It may be that your design is less efficient in 1.0. 
You could also share your vessel file so I can have a look.

**Comment by Mike0190** [comment] 2015-06-11 09:56
I'm 10000000% sure that the ship is fine because like I mentioned the very first time I used MJ it got me to the mun and back.. And literally every time I used it to fly the exact same craft it got less efficient on the gravity turn unrill the point (now) it won't even get into orbit, and absolutely nothing have been changed in settings or to the ship

**Comment by Mike0190** [comment] 2015-06-11 09:59
And by the way I did download the latest dev release and switched the files and I'm still having the same problem. And now i noticed it's not just that one ship. I tried it on a couple other ships of mine that I have orbited many many many times with no issues and it flattens out at around 16-20k and then starts heading back towards kerbin

**Comment by Mike0190** [comment] 2015-06-11 10:01
Just so everything is clear about what I said, when I said the first time I used MJ and it got me to the mun and back. That was literally hours ago. And it's gotten worse every time.

**Comment by sarbian** [comment] 2015-06-11 11:06
Try this : do in the gamedata/mechjeb2/plugin/plugindata/mechjeb2 (or something like this) and delete or move all the .cfg you ll find there and try again. This will reset all MJ config.

**Comment by lamont-granquist** [comment] 2018-12-16 22:05
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:05 UTC
