### ISSUE TITLE
Maneuver Planner: Match Planes should have more useful options.

### ISSUE THREAD

**Issue by Tallinu** [MuMech/MechJeb2#56] opened 2013-04-14 09:25 UTC
I don't know why anyone would care whether the plane-change happens at the AN or the DN, so the current two options make little sense to me. I would think that it would be much more useful to have the following two options: One that selects the next plane-crossing event regardless of whether it's ascending or descending, and one that selects the highest-altitude crossing to reduce the fuel required.

"At next AN or DN"
"At highest altitude plane intersection"

(And can we get the > arrow moved over next to the < arrow in all of these menus so that it doesn't jump around and it's easier to switch directions while browsing the options?)

**Comment by lamont-granquist** [comment] 2018-10-13 18:43
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-13 18:43 UTC
