### ISSUE TITLE
Spaceplane Guidance Flakey...

### ISSUE THREAD

**Issue by dapullia** [MuMech/MechJeb2#521] opened 2015-01-11 01:13 UTC
In .90 picking spaceplane guidance and then telling it to land on the either runway immediately results in your spaceplane entering final approach for a crash with the ground instead of actually flying to what would be a final approach fix and then entering final approach to landing on the runway.  The only way to prevent a crash is to put it into an altitude hold.  It seems like asking it to land should result in it automatically flying back to the selected runway fuel allowing then lining up and making a normal landing.

**Comment by sarbian** [comment] 2015-01-11 09:35
I am afraid that the spaceplane guidance is the neglected module. I don't really have the time or motivation to work on it now so it will not change much until someone volunteer.

**Comment by lamont-granquist** [comment] 2018-11-01 03:55
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 03:55 UTC
