### ISSUE TITLE
chasing the blue ball and not plotting planet transfers

### ISSUE THREAD

**Issue by hoffbrandm** [MuMech/MechJeb2#201] opened 2013-09-29 20:21 UTC
Hi,

Mechjeb doesnt seem to work at all for me, no matter how many times I create a new game etc.

My rocket seems to constantly chase the blue target reticule, either on manoeuvre planner or auto ascent or rendezvous.

Everything is fine until few seconds before the end of the maneuver, then it wable around like crazy.

Also whenever I try to get it to transfer to another planet, the blue target goes fucking nuts and the speed required (yellow m/s bar on the right) also goes crazy.

Whatever I have tried to do, I can't get anything to work, I just end up with a spinning rocket, or one with an insane and incorrect path.

Would very very very much appreciate help from you, i would love the amazing creation that is Mechjeb to work :)

really do appreciate your work

**Comment by lamont-granquist** [comment] 2018-10-13 21:58
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-13 21:58 UTC
