### ISSUE TITLE
Malfunction at ascending guidance

### ISSUE THREAD

**Issue by Wyrm82** [MuMech/MechJeb2#529] opened 2015-01-23 04:35 UTC
Hi there,
Thank you first for a wonderful mod.
I have a problem with ascending guidance.
First it works fine until reaching about 8-9km altitude, then suddenly mechjeb starts these,
timewarping to 2x while accelerating,
engine stuttering while throttle moving between 0 to 100% crazily,
nose pointing down.
Mechjeb goes back to normal in about half a minute and tries to regain control but then it is too late.
Rocket is stock kerbalX, and no other modifications done but mechjeb attached.
Both KSP and mechjeb are up to date versions and no other mods are installed.
Thank you.

**Comment by Felson** [comment] 2015-01-23 05:39
Which stock craft? Also, did it have RCA that you left shut off? I find that with long rockets, some times they have a hard time keeping there nose up.

**Comment by Wyrm82** [comment] 2015-01-23 06:20
Stock is Kerbal X. No RCAs. I did not make any modifications, just AR202 attached to command pod. 
It is not just keeping the nose up, Mechjeb seems to completely lose control.

**Comment by sarbian** [comment] 2015-01-23 10:36
Do you have any other mods ? Can you put your log file somewhere.
Did you change you ascent profile configuration ?

A stock KerbalX should not be able to trigger the condition to trigger the physical warp that soon.

**Comment by Wyrm82** [comment] 2015-01-25 01:57
Nope, no other mods.

**Comment by lamont-granquist** [comment] 2018-11-01 03:56
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 03:56 UTC
