### ISSUE TITLE
Flights in progress bug

### ISSUE THREAD

**Issue by worm22** [MuMech/MechJeb2#377] opened 2014-06-14 08:03 UTC
Used "Match planes with target" ... it set nodes for ALL "in progress" flights. If this is known and I just lacked the patience to find it, please continue with development and ignore me.  If not ... that's a pretty big issue as some "in progress" flights are pretty low on fuel and waiting for a refueling station to be set up nearby (was done while building a fueling station to send to Duna orbit).  Thanks.  LOVE the mod otherwise so far.

**Comment by lamont-granquist** [comment] 2018-11-01 01:46
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 01:46 UTC
