### ISSUE TITLE
Rendezvous Autopilot keeps failing

### ISSUE THREAD

**Issue by Masarath** [MuMech/MechJeb2#444] opened 2014-09-08 12:01 UTC
So, I launch my large craft in the attempt to dock it with my space station at 750km out. I use the Ascent Guidance to reach a stable orbit of 600km, then I select my station and activate the rendezvous autopilot.  It carries out the first few nodes fine, then, while attempting to match planes it burns at the wrong time. It will have set a maneuver to occur in an hour or so, but once it orientates itself, it carries out the node before reaching the correct point. I haven't had this issues with smaller craft and the first time I did it with the larger craft, it worked (had to revert flight due to a self made mistake in docking), but now it just can't seem to rendezvous with my target. I'm using quite a few mods, but the main ones are B9, Infernal Robotics, Kethane and KAS. 

The whole ship is 388 parts large on initial launch, dropping to roughly 200 parts when the problem is encountered.

If you need any more information, let me know.

**Comment by lamont-granquist** [comment] 2018-11-01 02:55
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 02:55 UTC
