### ISSUE TITLE
Initial options dissapear (DeltV, Orbit, Surface)

### ISSUE THREAD

**Issue by Fett2oo5** [MuMech/MechJeb2#268] opened 2013-12-27 17:38 UTC
When in campaign, I unlocked Mechjeb, initial options like Delta-V, Orbit information and Surface information were available.  After the next level of unlocking more Mechjeb options, these options are no longer available.  The only options are the custom window, and settings.  I've unlocked all but the 5 rightmost levels of the tree and still none of these options appear.  I uninstalled and reinstalled Mechjeb, didn't fix it.

**Comment by lamont-granquist** [comment] 2018-10-14 18:41
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 18:41 UTC
