### ISSUE TITLE
Launch into plane of target in ascent guidance not working at all

### ISSUE THREAD

**Issue by drhay53** [MuMech/MechJeb2#739] opened 2016-05-14 05:58 UTC
Basically, it just isn't working for me at all, and there's not really any rhyme or reason that I can tell. It launches at the completely wrong time to match planes every time. As posted in the thread on the KSP forums, here is an imgur album where I walk through the launch in screenshots:
http://imgur.com/a/CPNBL
MJ: release version 2.5.7
KSP 1.1.2

**Comment by drhay53** [comment] 2016-05-14 17:09
The results of some testing on dev builds versus the curse release version, posted also on the KSP forums:
 the 581 build appears to be 5 days newer than the 2.5.7 update date on curse. I'm on windows 10, 64 bit BTW.

I'll try testing the latest dev build, then 581 specifically, and also a fresh install.

Edit: updating this post with test results

test 1: fresh ksp 1.1.2 on mac osx with curse release MJ 2.5.7. FAILED same issue as the imgur album

test 2: same as above with MJ dev build 581: FAILED behavior is different though. launch 1 occurred at roughly the right time, but was still off by 400 delta-v. launch2 after 1 revert was off by a ton, complete failure. launch 3 after a 2nd revert was closer, 140 delta-v plane change. A 3rd revert produced a different launch time and a 400 delta-v plane change quite poor. because launch 2 was off by a couple of hours, this is definitely a fail.

test 3: 585 dev build: same as test 2. first launch timed pretty close, with 400 deltav plane change after orbit. 2nd launch however was completely on the wrong side of the planet. 1600 delta v plane change after orbit. '

It does seem to behave slightly better after a few reverts, more consistently launching at roughly the right time, although still several hundred deltav off in the final planes. however, the catastrophic failures I believe must be some kind of bug; it means i can't really trust the tool. Also, there's clearly a difference between the release version and the latest dev build. The release version seems to literally just pick random launch times.

**Comment by drhay53** [comment] 2016-05-15 17:42
Is it possible that a bug was introduced here:
https://github.com/MuMech/MechJeb2/commit/54e4019f5212b8a235e20b8021e09672fdf3613e

Suspiciously, the commit message says:
"Fix the ascent guidance launch into plane of target - you still need to launch once and revert to compute the LAN diff"

The 'you still need to' part, I have no idea where that's coming from as it's not in the manual. However, the first revert is usually the launch where the plane is horribly off; Usually I'm seeing launches after the first revert that are 90 degrees away from where they should be.

**Comment by lamont-granquist** [comment] 2018-11-01 04:39
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 04:39 UTC
