### ISSUE TITLE
request: Expected altitude entry for landing guidence

### ISSUE THREAD

**Issue by Felson** [MuMech/MechJeb2#527] opened 2015-01-21 06:30 UTC
A way to enter in the expected altitude where you are to touch down for landing. Better still would be t auto fill the box if you have SCANsat installed.

**Comment by sarbian** [comment] 2015-01-21 10:21
You want to choose the landing altitude ?? You land where you asked it to land ...

**Comment by Felson** [comment] 2015-01-21 16:50
When every I try and have it land anywhere not close to see level, it craters. I just assumed that mechjeb couldn't tell what the altitude was at the landing site, and there for couldn't do the math for when to slow down and stop.

**Comment by sarbian** [comment] 2015-01-21 18:05
No, it should know the landing height and adjust for that. There may be an other problem, but the landing AP is being worked on so it will improve. 
If you never used the dev release you could try it too, some bug are fixed in it.

**Comment by Felson** [comment] 2015-01-21 18:11
I think I may do that. This addon is the most useful addition to KSP out of all that I have seen by far.

**Comment by ErzengelLichtes** [comment] 2015-04-19 16:26
Maybe this request would be useful for all those "Perform Visual Survey of X region at 7,700 meters" Contracts? We could target the X region, set "target altitude" to 7,700 meters, do the visual survey, then engage the ascent guidance again?

**Comment by lamont-granquist** [comment] 2018-10-14 18:12
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 18:12 UTC
