### ISSUE TITLE
Porkchop plot not working

### ISSUE THREAD

**Issue by TheLoneWolfling** [MuMech/MechJeb2#600] opened 2015-06-02 14:21 UTC
The porkchop plot doesn't seem to be working (dev build 2.5.1.0-466):

```
[EXC 12:52:32.407] NullReferenceException: Object reference not set to an instance of an object
MuMech.OrbitExtensions.SwappedOrbitNormal (.Orbit o)
MuMech.OrbitExtensions.RelativeInclination (.Orbit a, .Orbit b)
MuMech.OperationInterplanetaryTransfer.MakeNodeImpl (.Orbit o, Double UT, MuMech.MechJebModuleTargetController target)
MuMech.Operation.MakeNode (.Orbit o, Double universalTime, MuMech.MechJebModuleTargetController target)
UnityEngine.Debug:LogException(Exception)
MuMech.Operation:MakeNode(Orbit, Double, MechJebModuleTargetController)
MuMech.MechJebModuleManeuverPlanner:WindowGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, GUISkin, Int32, Single, Single, GUIStyle)
```

This is with an asteroid tug that I keep having problems with (of the random rotation / acceleration leading to explosions variety) - perhaps that has something to do with it?

**Comment by sarbian** [comment] 2015-06-02 14:31
The plot works fine for me so I guess something is strange with the orbit itself. Could you share the save ?

**Comment by lamont-granquist** [comment] 2018-12-16 22:12
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:12 UTC
