### ISSUE TITLE
Advanced transfer (mun to min) error

### ISSUE THREAD

**Issue by Fyrem** [MuMech/MechJeb2#655] opened 2015-08-04 02:42 UTC
Started with a 20,000m alt over Mun, with Min as the target.
Opened build 500 of MJ, Advanced transfer to another planet, 
![image](https://cloud.githubusercontent.com/assets/13634879/9052050/b108ea14-3a17-11e5-8977-c168b62aedd6.png)

selected Lowest Dv 
Create node.
see result
![image](https://cloud.githubusercontent.com/assets/13634879/9052054/bbe42700-3a17-11e5-8991-8301fc5bcf62.png)

(or see imgur here http://imgur.com/a/LshwJ )

Repeatable at different alttitudes, different ships, and in Career and sandbox.

**Comment by lamont-granquist** [comment] 2018-12-16 22:32
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:32 UTC
