### ISSUE TITLE
Simplify the UI and integrated MechJeb 1.x.x with MechJeb 2.x.x

### ISSUE THREAD

**Issue by ghost** [MuMech/MechJeb2#58] opened 2013-04-16 21:49 UTC
To meet the criteria you established, I've revised the suggestion and request this be reopened.

The UI of MechJeb 2.x.x is extremely confusing when one compares it to MechJeb 1.x.x. Actions such as "circularize" are embedded in menus and submenus that are far more complicated than need be, and the plugin itself provides bare documentation for these changes. I suggest one of two things:

Either clarify the options within MechJeb 2.x.x (i.e., placing Orbital Operations back into the panel as it was with MechJeb 1.x.x); or

Create extensive documentation as to the new revisions for MechJeb 2.x.x that will be included in .rtf form with the plugin release.
- Golgotha

Original Text :: As it is, MechJeb 1.x.x did everything that 2.x.x did, but with better clarity and implementation. The only thing that MechJeb 2.x.x truly does better than before is docking with the automated Docking Autopilot. I  recommend merging the code, replacing the UI of MechJeb 1.x.x with the beautiful new MechJeb 2.x.x UI, and integrating the docking system.

**Comment by lamont-granquist** [comment] 2018-10-13 18:46
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-13 18:46 UTC
