### ISSUE TITLE
Drive: System.NullReferenceException

### ISSUE THREAD

**Issue by WuphonsReach** [MuMech/MechJeb2#547] opened 2015-03-04 00:10 UTC
Taken from output_log.txt -- seems to happen on staging events.  Possibly when I have multiple AR202 units?

(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

RemoteTech: SatelliteManager: Register(ModuleSPU(, 0058e8c3-7fce-460f-986b-e7c8c9711709))

(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

[00:07:44]: Separation of stage 4 confirmed

(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

MechJeb module MechJebModuleThrustController threw an exception in Drive: System.NullReferenceException: Object reference not set to an instance of an object

  at MuMech.MechJebModuleThrustController.FlameoutSafetyThrottle () [0x00000] in <filename unknown>:0 

  at MuMech.MechJebModuleThrustController.Drive (.FlightCtrlState s) [0x00000] in <filename unknown>:0 

  at MuMech.MechJebCore.Drive (.FlightCtrlState s) [0x00000] in <filename unknown>:0 

(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

OnVesselSituationChanged

(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

[FLIGHT GLOBALS]: Switching To Vessel Kerb-Comm Y1D166ABCD Mercury I (XXXkm) Probe ---------------------- 

(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

stage manager resuming...

**Comment by sarbian** [comment] 2015-03-04 08:58
Did you have an AR202 on each stage ? Do you get it each time you stage ?

**Comment by WuphonsReach** [comment] 2015-03-06 05:30
It does seem to be any instance where I have multiple AR202s.  I get it right as soon as I load to the launchpad.

**Comment by Viruzzz** [comment] 2015-03-08 02:59
i have almost same error :(
I take from KSP.log

[ERR 02:54:50.423] MechJeb module MechJebModuleThrustController threw an exception in Drive: System.InvalidOperationException: Operation is not valid due to the current state of the object
  at System.Linq.Enumerable.Iterate[Part,Single] (IEnumerable`1 source, Single initValue, System.Func`3 selector) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.Max[Part] (IEnumerable`1 source, System.Func`2 selector) [0x00000] in <filename unknown>:0 
  at MuMech.MechJebModuleThrustController.TemperatureSafetyThrottle () [0x00000] in <filename unknown>:0 
  at MuMech.MechJebModuleThrustController.Drive (.FlightCtrlState s) [0x00000] in <filename unknown>:0 
  at MuMech.MechJebCore.Drive (.FlightCtrlState s) [0x00000] in <filename unknown>:0 

[EXC 02:54:50.426] NullReferenceException
	UnityEngine.Component.get_gameObject ()
	Vessel.recurseCoMs (.Part part)
	Vessel.recurseCoMs (.Part part)
	Vessel.findWorldCenterOfMass ()
	MuMech.VesselState.UpdateBasicInfo (.Vessel vessel)
	MuMech.VesselState.Update (.Vessel vessel)
	MuMech.MechJebCore.FixedUpdate ()
[EXC 02:54:50.431] NullReferenceException
	UnityEngine.Component.get_gameObject ()
	Vessel.recurseCoMs (.Part part)
	Vessel.recurseCoMs (.Part part)
	Vessel.findWorldCenterOfMass ()
	Vessel.FixedUpdate ()


With this bug i can't go back at base or changing the vessel. etc...

**Comment by lamont-granquist** [comment] 2018-11-01 04:02
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 04:02 UTC
