### ISSUE TITLE
NullReferenceException Hitting whenever undocked,but goes away when docked.?????

### ISSUE THREAD

**Issue by drtedastro** [MuMech/MechJeb2#267] opened 2013-12-24 04:34 UTC
H'mmm, I have 'interesting' bug / problem that I think 'might' be associated with MJ...
I am running the latest release. I have a sat deployment system that has worked in previous releases. Now when I deploy one of the sats, I start getting exceptions thrown into the ksp.log. Even when i undock from the carrier, the same happens.

I have looked through the log(s) and here is the culprit, I think.

[LOG 17:42:05.645] RemoteTech: SatelliteManager: Register(ModuleSPU(, ca4df6d3-3cd0-4038-916e-ce5a2efe1500))
[ERR 17:42:05.673] MechJeb caught exception in core OnSave: System.NullReferenceException: Object reference not set to an instance of an object
at MuMech.MechJebCore.OnSave (.ConfigNode sfsNode) [0x00000] in <filename unknown>:0 
[ERR 17:42:05.832] MechJeb module MechJebModuleThrustController threw an exception in Drive: System.NullReferenceException: Object reference not set to an instance of an object
at MuMech.CelestialBodyExtensions.RealMaxAtmosphereAl titude (.CelestialBody body) [0x00000] in <filename unknown>:0 
at MuMech.VesselState.TerminalVelocity () [0x00000] in <filename unknown>:0 
at MuMech.MechJebModuleThrustController.TerminalVeloc ityThrottle () [0x00000] in <filename unknown>:0 
at MuMech.MechJebModuleThrustController.Drive (.FlightCtrlState s) [0x00000] in <filename unknown>:0 
at MuMech.MechJebCore.Drive (.FlightCtrlState s) [0x00000] in <filename unknown>:0 
[EXC 17:42:05.838] NullReferenceException: Object reference not set to an instance of an object
[EXC 17:42:05.856] NullReferenceException: Object reference not set to an instance of an object
[LOG 17:42:07.311] Target: None

[EXC 17:42:07.334] NullReferenceException: Object reference not set to an instance of an object
[EXC 17:42:07.349] NullReferenceException: Object reference not set to an instance of an object
[EXC 17:42:07.400] NullReferenceException: Object reference not set to an instance of an object
[EXC 17:42:07.415] NullReferenceException: Object reference not set to an instance of an object
[EXC 17:42:07.458] NullReferenceException: Object reference not set to an instance of an object

Please let me know of any other info, tests or such that I can provide.
Thanks sarbian for all of your fantastic work. MJ is the #1 mod for me......

**Comment by lamont-granquist** [comment] 2018-10-14 18:40
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 18:40 UTC
