### ISSUE TITLE
2-2.2.1.257 bugs in ascent guidance

### ISSUE THREAD

**Issue by BigTexun** [MuMech/MechJeb2#375] opened 2014-06-07 19:03 UTC
So I generally like to manually launch to orbit, because I can usually do it wasting less fuel than mechjeb, which tends to overshoot and constantly correct, when I can anticipate and prevent overshoot.

So I will use it to time the launch, then disengage and select "show navball ascent guidence", then launch into orbit by hand, using the navball guidence as a visual aid.

So the "bug" is that when I hit the "show navball ascent guidence" button, my target is de-selected.  Of course there is no ascent guidance now, because there is no target.  Ooops!

In the flight attempts going to the same asteroid, I try to use one of the "launch to interplanetary window" or "Launch to redevous", the orbit escape burn crashes be into Kerbin.  In my last attempt, I made sure the maneuver node looked sane, but when I executed is started the burn well before the node, and the resulting trajectory looks like it was trying to sling-shot around the Kerban center of gravity, well within the inside of the planet.  

I know I can avoid these issues, there is a thousand different ways to do everything, but these seemed like bugs to me.

**Comment by lamont-granquist** [comment] 2018-10-14 19:35
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 19:35 UTC
