### ISSUE TITLE
Simply Crashes

### ISSUE THREAD

**Issue by wolverine79936** [MuMech/MechJeb2#875] opened 2017-03-30 03:52 UTC
Whenever I try to run Mechjeb 2.6.0 and KSP 1.2.2, it just comes up and says oops! And then that is it. The game crashes. I looked through the log files and it says "The thread tried to read from or write to a virtual address for which it does not have the appropriate access." I tried running ksp with Mechjeb 2.6 as an admin and it still threw the same error. BTW, I'm running KSP 1.2.2 x64 and x32 and it is giving the same error on Windows 10. Don't like Win 10. :(

**Comment by lamont-granquist** [comment] 2018-12-16 22:52
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:52 UTC
