### ISSUE TITLE
Orbit Failure

### ISSUE THREAD

**Issue by merphyscode** [MuMech/MechJeb2#876] opened 2017-03-31 03:39 UTC
Hi guys (and gals) First of all I would like to say what your doing here is really cool, So thanks. I downloaded Mechjeb yesterday, for version 1.2.2 off GIT. Running just MJ no other mods. I tried using it to get to orbit today and it REALLY messed up the circulation and DESTROYED the angle of inclination. 

Picture here:
http://steamcommunity.com/app/220200/discussions/0/135512931350951550/

As you can see 0 degree inclination and 100km circular orbit did not happen.
any idea whats wrong? Is it due to the fact that I am running the 64bit version?
definitely the most up-to-date MJ and i just clean installed KSP a yesterday too. 

Some people said it was because I made a shit rocket so i tried again with the satellite already in orbit, here is a walk threw of what happened

_____________________________
Here is my current orbit:
http://steamcommunity.com/sharedfiles/filedetails/?id=894973703
notice 123km by 134km and on a orbital inclination of 11.180
_____________________________
Here is my satellite (not bad)
http://steamcommunity.com/sharedfiles/filedetails/?id=894973630
Its got fuel and all that jaz... also notice i am telling mechjeb to make it into a 110km orbit on the same inclination.
_____________________________
And HERE is what i got after i run the autopilot... 
http://steamcommunity.com/sharedfiles/filedetails/?id=894973726
notice the 134km by 85km orbit i am now sitting in...
_____________________________

Help? =[
the ONLY thing i can think of is that i have played this save on both 32 and 64bit versions of the game...

If there is any debug information i can provide please just let me know what it is and how to get to it and i will get it for you as soon as i can. I am running windows 7 x64 via steam (obviously) and i have MJ 2.6.0.0 and KSP 1.2.2
Thanks

RE:Sorry didn't rtm of posting here about where uploading logs, I did a clean install with MJ for the 4th time and it seems it MAY have worked. Ill test more tomorrow and if it is not ill post the log. And ill update this either way, 
else ( 
        for ( 1 - 3 ) {
                           successful_install = 0
                          }
        for ( 4 ) {
                          successful_install = 1
                     }
)

For now it is time for me to hit the sack.

**Comment by lamont-granquist** [comment] 2018-12-16 22:52
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:52 UTC
