### ISSUE TITLE
RCS keeps getting enabled when toggling autopilot and when staging

### ISSUE THREAD

**Issue by Gouvernathor** [MuMech/MechJeb2#1860] opened 2024-02-10 23:17 UTC
I didn't find any option to disable that in the ascent autopilot settings.
This is using my RCS reserves without asking for permission, kinda rude.

When I'm on the landing pad, the mod doesn't even allow me to deactivate RCS !

**Comment by Gouvernathor** [comment] 2024-02-11 17:37
It also triggers during landing guidance, whenever the thrust is very low, it seems. I have to spend a lot of time just shutting off the RCS, it's very annoying and borders unplayable.

**Comment by Sinomen** [comment] 2024-03-14 11:51
RCS is always active when enabling MJ, be it Ascent Guidance, be it Node Execution. No Kopernicus/RO/RSS installed. This bug is persistent since build #1344.

**Comment by Starwaster** [comment] 2024-03-17 16:09
Sounds like RCS auto mode is on. There is a setting for that in the attitude adjustment window.

**Comment by Gouvernathor** [comment] 2024-03-18 23:38
The "RCS auto mode" is disabled in the attitude adjustment window, which I never opened before.
The one in landing guidance is still enabled, but I suppose (as it did before) that that setting only changes anything for specific moments during the landing autopilot, and not to unrelated modules (ascent guidance or auto maneuver for example).

**Comment by Sinomen** [comment] 2024-03-20 14:18
> Sounds like RCS auto mode is on. There is a setting for that in the attitude adjustment window.
> 
> (and the landing guidance window has a similar RCS control for killing lateral motion)

RCS auto mode is off, never was on. As I said, the issue came up with #1344, never before, and is persistent since.

**Comment by Starwaster** [comment] 2024-03-20 22:37
@Sinomen Narrow that down to Real Fuels which you can have installed independently of RO or RSS. That is what is being looked for.
That said, it should only ever trigger if commanded throttle is > 0 and there is unstable ullage, so it's clearly missing some checks. There's only 4 files where AutoRCSUllaging is referenced so it shouldn't be too hard to find.

**Comment by Sinomen** [comment] 2024-03-21 06:32
No Real Fuels installed here.

**Comment by Starwaster** [comment] 2024-03-21 13:12
If you don't even have RF installed then that is definitely a problem, but it should make it easier to track down. I'm on my phone so I'll have to wait until I'm back on my PC to comment further.

**Comment by Gouvernathor** [comment] 2024-03-21 13:41
No Real Fuels either on my side.

**Comment by Starwaster** [comment] 2024-03-21 13:50
https://github.com/MuMech/MechJeb2/blob/12368452ea88c8584f80866bf0ffc55276d4a053/MechJeb2/MechJebModuleStagingController.cs#L300
https://github.com/MuMech/MechJeb2/blob/12368452ea88c8584f80866bf0ffc55276d4a053/MechJeb2/MechJebModuleNodeExecutor.cs#L140
https://github.com/MuMech/MechJeb2/blob/12368452ea88c8584f80866bf0ffc55276d4a053/MechJeb2/MechJebModuleThrustController.cs#L101

I am leaning towards this being in the thrust controller but it could be a bit deeper where it actually checks ullage. Without RF installed, all ullage checks are supposed to be assumed stable but I don't like the way that's implemented at that level. There's no sanity check and it depends on an update to actually SET the field as stable, and that leads to race conditions. 

(I said 4 but this last one is just ascent guidance settings, it doesn't touch RCS itself)
https://github.com/MuMech/MechJeb2/blob/12368452ea88c8584f80866bf0ffc55276d4a053/MechJeb2/MechJebModuleAscentSettings.cs#L343

**Comment by Gouvernathor** [comment] 2024-03-21 15:27
I don't know how to generate logs, but in any case the bug happens on the launchpad so you don't need to wait "in flight mode" to see it.

**Comment by Starwaster** [comment] 2024-03-21 15:40
I should have said flight scene which includes the pad, prelaunch, landed, etc. 

Logs are in the KSP folder and they're always generated. 

I can make a pull request that might  fix this but I won't be able to build it and test it myself because I'm not set up for it. But it might not be enough which is why I'd like to check someone's log for some things.

**Comment by Sinomen** [comment] 2024-03-21 15:59
> Would one of you two mind posting your logs when you've been in flight mode long enough for this to happen?

Which log file(s) exactly? KSP.log? And, I assume, with AutoRCSUllaging  = True?

**Comment by Sinomen** [comment] 2024-03-21 17:06
Reminds me of Autostaging issue #1658: changes were made, things went broke.

**Comment by Starwaster** [comment] 2024-03-21 17:14
> > Would one of you two mind posting your logs when you've been in flight mode long enough for this to happen?
> 
> 
> 
> Which log file(s) exactly? KSP.log? And, I assume, with AutoRCSUllaging  = True?

Yes and yes.

**Comment by Starwaster** [comment] 2024-03-21 18:52
Never mind the log. I made new install with just MJ/MM and I didn't see what I was looking for.

I could only partially replicate it though. It happened anytime I tried to throttle up but not when staging or using other autopilot functions. And enabling the auto RCS in attitude adjustment didn't turn RCS off reliably. I don't think that's related to this bug though.

**Comment by Sinomen** [comment] 2024-03-22 05:41
For me, it definitely happens using the Ascent Guidance and the Node Execution, other MJ functions I only use rarely.

**Comment by Gouvernathor** [comment] 2024-03-22 16:08
For me, it happens not only when you throttle up (manually), but also maybe one second _ahead_ of firing the engine when executing a maneuver node.

Maybe we can send our saved settings to you ?

**Comment by Starwaster** [comment] 2024-03-22 18:13
It's the ship I tested with. While technically stageable, it didn't have multiple stages. That was why it didn't happen for me at first.

**Comment by Sinomen** [comment] 2024-03-23 13:32
> For me, it happens ...  maybe one second _ahead_ of firing the engine when executing a maneuver node.

Which totally makes sense, the problem is the forced RCS ullaging.

**Comment by Starwaster** [comment] 2024-03-26 12:55
The pull request I made was merged in. Try the latest dev build.

**Comment by Gouvernathor** [comment] 2024-03-26 18:21
Nope, RCS is still enabled and impossible to deactivate when on the launchpad.

**Comment by Sinomen** [comment] 2024-03-28 10:34
> Nope, RCS is still enabled and impossible to deactivate when on the launchpad. RCS still enables itself around 1s before starting a maneuver node.

I concur.

**Comment by lamont-granquist** [comment] 2024-03-28 19:22
#1876 should fix the node executor RCS issue but i didn't test.

**Comment by lamont-granquist** [comment] 2024-03-28 19:39
#1877 may fix the rest of it

**Comment by Gouvernathor** [comment] 2024-03-28 20:54
It is now possible to deactivate RCS while on the launchpad. However, it is still enabled by default, and still enables itself on its own when executing a maneuver burn.

**Comment by lamont-granquist** [comment] 2024-03-30 18:56
> still enables itself on its own when executing a maneuver burn.

Do you somehow have "RCS Burn" checked in the maneuver planner?

**Comment by Gouvernathor** [comment] 2024-03-31 22:39
Nope.

**Comment by Gouvernathor** [comment] 2024-04-14 13:33
@lamont-grandquist @Starwaster any news ?

**Closed** 2024-04-24 23:53 UTC

**Comment by Gouvernathor** [comment] 2024-04-25 21:31
That seems to finally work !!
