### ISSUE TITLE
Limit to terminal velocity active in terminal node before Utilities module is unlocked.

### ISSUE THREAD

**Issue by pjwerneck** [MuMech/MechJeb2#292] opened 2014-02-01 02:12 UTC
Pretty much what the title says. While playing in career mode, I noticed my throttle during ascent was being adjusted as if the "Limit to terminal velocity" was enabled, even though the Utilities module was still locked and not visible on the menu.

**Comment by lamont-granquist** [comment] 2018-10-14 19:07
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 19:07 UTC
