### ISSUE TITLE
Cant find mechjeb parts

### ISSUE THREAD

**Issue by pugs30th** [MuMech/MechJeb2#982] opened 2018-01-30 23:39 UTC
Updated to the newest KSP today 1.3.1.1891

Got mechjeb 2.7.0 through Twitch.  Seems to be installed properly(in Gamedata)

The AR202 and MechJeb pod are nowhwere to be found in the game.  I have tried a new sandbox mode even.

What am I missing?

**Comment by topguns60** [comment] 2018-02-06 14:40
exactly same issue for me
an answer  ?

**Comment by sarbian** [comment] 2018-02-06 14:50
Not without a log.

**Comment by topguns60** [comment] 2018-02-06 15:01
ok but how can i have log ?

**Comment by sarbian** [comment] 2018-02-06 15:21
https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/#Logs

**Comment by topguns60** [comment] 2018-02-06 15:46
thanks
i am going to look at this  later

**Comment by lamont-granquist** [comment] 2018-12-26 00:06
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-26 00:06 UTC
