### ISSUE TITLE
Airless body+Auto-warp problem

### ISSUE THREAD

**Issue by tenshi99** [MuMech/MechJeb2#822] opened 2016-11-26 11:48 UTC
During landing with help of "Landing Guidance" on Minmus i noticed jumpy turns of Minmus in process. They made landing utterly inaccurate(even cause destruction if jump into terrain like hills). Later i noticed similar problem with ascent+circularization. Vessel moved far away from its trajectory, and make all maneuver nodes unfit. After some testing i has identified problem, its timewarp(non-physical). It make bodies at low altitudes to skip, physical timewarp dont have this problem. Skip occured at altitude below 100km(on Mun other bodies have other values) and lower altitude = more harsh skip. 
Can you use physical timewarp at lower altitudes instead non-physical?

**Comment by lamont-granquist** [comment] 2018-12-16 22:42
Duplicate of all the issues rolled up under #1052

**Closed by lamont-granquist** 2018-12-16 22:42 UTC
