### ISSUE TITLE
FuelFlowSimulation.SimulateStage reached max step count of 100

### ISSUE THREAD

**Issue by bdew** [MuMech/MechJeb2#818] opened 2016-11-17 01:07 UTC
This broke with one of the last chages. Build 647 worked correctly, 651 spams the following in the log and doesn't calculate dV with any liquid fuel engine on the craft:

    [MechJeb2] Exception in MechJebModuleStageStats.RunSimulation(): System.Exception: FuelFlowSimulation.SimulateStage reached max step count of 100
      at MuMech.FuelFlowSimulation.SimulateStage (Single throttle, Double staticPressure, Double atmDensity, Double machNumber) [0x00000] in <filename unknown>:0 
      at MuMech.FuelFlowSimulation.SimulateAllStages (Single throttle, Double staticPressureKpa, Double atmDensity, Double machNumber) [0x00000] in <filename unknown>:0 
      at MuMech.MechJebModuleStageStats.RunSimulation (System.Object o) [0x00000] in <filename unknown>:0 
      
Full log is here if you want it: https://www.dropbox.com/s/8j2beu9dqha1rbf/output_log.txt?dl=0

**Comment by lamont-granquist** [comment] 2018-12-16 22:33
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:33 UTC
