### ISSUE TITLE
Launching closes all MJ windows

### ISSUE THREAD

**Issue by BloodyRain2k** [MuMech/MechJeb2#865] opened 2017-03-07 07:01 UTC
I don't know why but given the specific nature of this "bug" I assume it's more of an (to me) unintuitive feature.
Whenever I launch a new rocket or plane ALL (except custom) MJ windows are closed.

Even if you switch to another plane they will still be closed so they are not remembered on a per vessel state but rather discarded globally, for whatever reason.

I really prefered the previous way of handling it where it just left the global last state alone.

**Comment by sarbian** [comment] 2017-03-07 18:19
Err, nope I don't have this here.

**Comment by BloodyRain2k** [comment] 2017-03-07 23:46
That's what I feared. I already cleared my whole MJ data folder (minus the part about my custom windows because hell will freeze over before I recreate these yet again) and it still happens every single time.
From what little debugging I managed to make is it for some reason forgetting what's saved in the global config upon scene change :<

It's not that the config is null and completely missing but it just seems empty and therefore result in "false" for the showInFlight loading attempt, and I don't get why.

**Comment by lamont-granquist** [comment] 2018-12-24 19:13
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-24 19:13 UTC
