### ISSUE TITLE
Factory Reset confirmation

### ISSUE THREAD

**Issue by BloodyRain2k** [MuMech/MechJeb2#832] opened 2016-12-11 06:02 UTC
I've just accidentally nuked my settings.

For some reason was the settings window open when I went to my sandbox save to check something and my brain derped and pressed the biggest button in that window to close it.

The closing worked atleast, except that every single window closed and now all my custom windows and PID settings are gone : (

So please someone add a confirmation dialog to it or make it a button you need to hold for a sec like the quickreload key does. I gotta find a window back in some old copy now...

**Comment by lamont-granquist** [comment] 2018-12-16 22:32
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:32 UTC
