### ISSUE TITLE
MJ stages although it shouldn't using rendevouz ascent guidance

### ISSUE THREAD

**Issue by MarkusHaslinger** [MuMech/MechJeb2#516] opened 2015-01-05 18:17 UTC
When using the ascent guidance in "normal" mode everything is fine, but when using the "launch to rendevouz" option MJ stages (~7 sec after launch) although auto-stage is ticked off or a certain max stage is defined.

Functionality is working in build 378
Functionality is broken in build 382

Sarbian said he changed something in build 379 which might cause this (hello sarbian! ;)

**Comment by lamont-granquist** [comment] 2018-11-01 03:55
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-11-01 03:55 UTC
