### ISSUE TITLE
2.09 will not dock using docking autopilot.

### ISSUE THREAD

**Issue by Acecool** [MuMech/MechJeb2#205] opened 2013-10-09 20:05 UTC
So, I had 500 units of fuel for rcs and enabled the docking autopilot for 1 of 5 available slots on my space station, and 1 of 4 on the ship ( control from here ). It ended up continuously swiveling around and not docking. After about 100 fuel was left it knocked off one of my solar panels on my space station, and I hope it didn't save otherwise I'm finished with this mod as it took forever to get that space station in orbit and built....

I was trying to dock docking port extensions...

**Comment by lamont-granquist** [comment] 2018-10-13 21:55
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-13 21:55 UTC
