### ISSUE TITLE
delta-v calculations and maneuver node timings fail for rocket with high part count

### ISSUE THREAD

**Issue by raygundan** [MuMech/MechJeb2#387] opened 2014-07-14 03:36 UTC
I'm not sure what the root cause is here, but I have two similar rockets.  One has 630 parts, and while the upper stage is complicated, the lift stages are identical to the simple version with the dummy payload.

The complex payload will fly just fine manually, but MechJeb is weird with it:

-No Delta-V calculations ever display, whether in the VAB, on the pad, or during flight, regardless of whether the cosine loss toggle is checked.
-Any attempt to fly a maneuver node automatically will start the burn exactly at the maneuver node, rather than starting the burn ahead of the node.  The burn time calculations in the game appear to be correct, though-- MechJeb is just ignoring the value and starting at 0.

The version with the dummy payload and much lower part count flies fine with MechJeb, and the Delta-V calculations work as expected.  I can provide both .craft files if needed, although it appears I can only attach images here.

![2014-07-13_00006](https://cloud.githubusercontent.com/assets/3998507/3566903/76b49182-0b07-11e4-8beb-7ddf80af3124.jpg)
![2014-07-13_00007](https://cloud.githubusercontent.com/assets/3998507/3566904/78bc3156-0b07-11e4-857b-792fc57adb08.jpg)
![2014-07-13_00008](https://cloud.githubusercontent.com/assets/3998507/3566905/7af3c2c2-0b07-11e4-85bb-a1879655123f.jpg)

**Comment by lamont-granquist** [comment] 2018-10-14 21:08
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 21:08 UTC
