### ISSUE TITLE
Suggestions to Improve the Spaceplane Guidance

### ISSUE THREAD

**Issue by Mogeley** [MuMech/MechJeb2#249] opened 2013-12-09 07:05 UTC
I'd like to help with improving the spaceplane autopilot. I wrote an aircraft autopilot for Orbiter so I have some experience with this. If I have time to code any changes where should I put those changes?

Here's my observations of what could be improved.
1) Control surfaces have an infinite rate of change. These should be clamped down so the control surfaces have a maximum rate in which they can be moved. Snapping control surfaces too quickly around can cause instability in flight.
2) Flight control should be based on the aircraft's Flight Path. Pitch, bank angle, and yaw is a tool to get to the target heading & slope with their own restrictions like max AOA and max bank.
3) The autopilot needs to also be able to control the throttle, especially for landing. When landing real planes the aircraft pitch and throttle trade positions. Airspeed is managed by pitch and the flight slope by the throttle.
4) Max roll should be at least 60 degrees. A 60 degree turn is 2G's (on earth)

Once these are set creating a flight path to a location and landing is quite easy. My autopilot for Orbiter will do fully automatic flights to other spaceports.

**Comment by lamont-granquist** [comment] 2018-10-14 18:49
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-10-14 18:49 UTC
