### ISSUE TITLE
Build 511; Engine-Restart will not work in automated processes

### ISSUE THREAD

**Issue by hraban35** [MuMech/MechJeb2#662] opened 2015-08-29 08:11 UTC
After a Time-Warp process the restart of a stage engine will not work correct (randomly) in all phases of a:
- automated Launch
- automated rendezvous

Only way to restart the engine of the stage is to interupt the automated process and start it again.

Greetings

**Comment by sarbian** [comment] 2015-08-29 08:19
Are you using other mods ? RO / RSS ?

**Comment by hraban35** [comment] 2015-08-29 10:18
Hello Sarbian,

i dont use mods like RO, RSS, FAR. in this case im on Stock. Only Part-Mods like Nova-Punch, KIS, TAC and Trajectories are used.

**Comment by robot256** [comment] 2016-01-05 15:02
Could there be an issue with pointing your ship?  Mechjeb will not turn on the engine if you are pointed in the wrong direction, and your craft might not be able to turn without RCS.

Is the random decoupler problem only when Mechjeb is autostaging during ascent, or with manual staging also?  Mechjeb normally does not autostage during other maneuvers.  Are you running the 64-bit version of KSP?  I remember it had some weird bugs like that.

**Comment by lamont-granquist** [comment] 2018-12-16 22:31
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:31 UTC
