### ISSUE TITLE
Orientation 

### ISSUE THREAD

**Issue by anthony-france** [MuMech/MechJeb2#564] opened 2015-04-28 03:30 UTC
http://imgur.com/a/Csiay

http://i.imgur.com/tviSksW.jpg  - The build engineer has no issues with alignment of any control pods on this vessel, however notice they are 90 degrees from each other.

http://i.imgur.com/wpDFT58.jpg - The AR202 is moved to be on the same side as the main control pod.  The engineer flags this as incorrect.

http://i.imgur.com/J6tBqBo.jpg - The AR202 is left in place and rotated to face the same direction as the AR unit.

I'm not sure if this is by design or unexpected.  Maybe there is some documentation I missed but just noticed it with the addition of the build check tool.

**Comment by sarbian** [comment] 2015-04-30 09:34
Not by design but I am not sure I can easily fix it...

**Comment by afrance** [comment] 2015-04-30 14:03
Yeah, I've never ended up running into any problems in the past due to it,

It helps explain some odd landing or docking orientations orientations but I guess as long as it knows which directions are which its not the largest issue anyway.  I had heard early on there were some landing issues in with ksp 1.0 and figured I'd post about this in case it helped lead down the path to fix the landing or something else... I never really thought of pod orientation because the rotation doesn't seem to readily effect the nav ball, certainty not like the effects of turning one upside down.

Also, once I was out on the pad if i right clicked and used control from here the orientation on the nav ball didn't change 90 degrees like you might expect.

**Comment by lamont-granquist** [comment] 2018-11-26 21:32
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

And I'd really encourage not using the AR202 and just using one of the MechJebForAll MM patches.

**Closed** 2018-12-16 22:13 UTC
