### ISSUE TITLE
Interplanetary fine tune closest approach to target

### ISSUE THREAD

**Issue by johnwayne1930** [MuMech/MechJeb2#806] opened 2016-10-18 19:47 UTC
As I last played KSP in v1.1.2 the "fine tune closest approach to target" option did a rendezvous maneuver to intercept a targeted planet with the minimal possible dV usage.
Now in KSP 1.2 with MJ build 644 it seems to do a instant to execute maneuver for the fastest route to the targeted planet, which costs an awful lot of dV more than necessary.

**Comment by lamont-granquist** [comment] 2016-10-19 06:46
What is the process that you're going through to setup the rendezvous?

**Comment by johnwayne1930** [comment] 2016-10-19 09:24
I use the regular "transfer to another planet" option in maneuver planer, where MJ choose the next matching transfer window, out of an Kerbin orbit.
Not the advanced stuff, also not the as soon as possible option.

**Comment by absincog** [comment] 2016-10-19 15:20
If you are using the 'Launch at interplanetary window function' in ascent guidance, this may be related to issue 763 which I originally opened as issue 738 in May (it was erroneously closed so I reopened as 763 in June).  Bottom line is that the launch at interplanetary window functionality has been broken for months now.  It does not accurately choose the window, leaving a huge dV to complete and/or fine tune the transfer.  I am also suspicious whether the 'transfer to another planet' is accurately choosing the correct window.

**Comment by johnwayne1930** [comment] 2016-10-19 19:50
No I started "transfer to another planet" from an orbit around Kerbin.
But now as you mention it I checked and that doesn't look like the right [transfer window](http://i.imgur.com/5iQNaf2.jpg).
Which would explain why "fine tune closest approach" does not well, because there is no real closest approach happening.

**Comment by lamont-granquist** [comment] 2016-10-19 22:38
so it sounds like this is more related to ascent guidance timing of launch issues and more like the #807 issue that i just cut...

**Comment by absincog** [comment] 2016-10-21 15:46
The 'launch at interplanetary window' function used to accurately determine the launch timing based on selection of the destination planet as the target.  Upon engaging the auto pilot, Ascent Guidance would then time warp to the launch window, launch the craft and achieve the desired Kerbin orbit.  Once in Kerbin orbit, you could then use the maneuver planner to transfer to the target planet - typically the 'launch to interplanetary window function' would have left a buffer of <1 hour of "in game" time before the transfer.

Since May; however, the function no longer accurately computes the window, leaving a random time period to the transfer window once in Kerbin orbit (I've experienced time frames ranging from ~40 - 220 days).

**Comment by lamont-granquist** [comment] 2018-12-16 22:34
Closing this as an old MechJeb issue.  Many MechJeb issues have had little interest in years, have been fixed for years, do not include adequate replication steps, refer to old problems which are no longer applicable, or are difficult to determine what the problem is.  This issue is being closed for one of those reasons.  We apologize for any inconvenience, but keeping the TODO list tidy helps the developers.

If this bug/issue is still a problem, please open a new issue.  For bugs please try to include a [Minimal, Complete, Verifiable Example](https://stackoverflow.com/help/mcve) that explains all the steps required to replicate the issue.  A link to the KSP.log file should be ideally included, but is often not sufficient information.  Screenshots or short videos are often the best way to show a bug.

**Closed by lamont-granquist** 2018-12-16 22:34 UTC
